
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.ts'
export { Prisma }
export * as $Enums from './enums.ts'
export * from './enums.ts';
/**
 * Model Project
 * 
 */
export type Project = Prisma.ProjectModel
/**
 * Model ProjectMember
 * 
 */
export type ProjectMember = Prisma.ProjectMemberModel
/**
 * Model OrgProject
 * 
 */
export type OrgProject = Prisma.OrgProjectModel
/**
 * Model Org
 * 
 */
export type Org = Prisma.OrgModel
/**
 * Model Membership
 * 
 */
export type Membership = Prisma.MembershipModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model ApiKey
 * 
 */
export type ApiKey = Prisma.ApiKeyModel
/**
 * Model ApiLog
 * 
 */
export type ApiLog = Prisma.ApiLogModel
/**
 * Model VerificationCode
 * 
 */
export type VerificationCode = Prisma.VerificationCodeModel
/**
 * Model DataSource
 * 
 */
export type DataSource = Prisma.DataSourceModel
/**
 * Model Chart
 * 
 */
export type Chart = Prisma.ChartModel
/**
 * Model SourceLink
 * 
 */
export type SourceLink = Prisma.SourceLinkModel
/**
 * Model Dashboard
 * 
 */
export type Dashboard = Prisma.DashboardModel
/**
 * Model Slot
 * 
 */
export type Slot = Prisma.SlotModel
