
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.ts"
import * as $Class from "./internal/class.ts"
import * as Prisma from "./internal/prismaNamespace.ts"

export * as $Enums from './enums.ts'
export * from "./enums.ts"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Projects
 * const projects = await prisma.project.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model Project
 * 
 */
export type Project = Prisma.ProjectModel
/**
 * Model ProjectMember
 * 
 */
export type ProjectMember = Prisma.ProjectMemberModel
/**
 * Model OrgProject
 * 
 */
export type OrgProject = Prisma.OrgProjectModel
/**
 * Model Org
 * 
 */
export type Org = Prisma.OrgModel
/**
 * Model Membership
 * 
 */
export type Membership = Prisma.MembershipModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model ApiKey
 * 
 */
export type ApiKey = Prisma.ApiKeyModel
/**
 * Model ApiLog
 * 
 */
export type ApiLog = Prisma.ApiLogModel
/**
 * Model Code
 * 
 */
export type Code = Prisma.CodeModel
/**
 * Model DataSource
 * 
 */
export type DataSource = Prisma.DataSourceModel
/**
 * Model Chart
 * 
 */
export type Chart = Prisma.ChartModel
/**
 * Model SourceLink
 * 
 */
export type SourceLink = Prisma.SourceLinkModel
/**
 * Model Dashboard
 * 
 */
export type Dashboard = Prisma.DashboardModel
/**
 * Model Slot
 * 
 */
export type Slot = Prisma.SlotModel
