
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User.ts'
export type * from './models/Code.ts'
export type * from './models/DataSource.ts'
export type * from './models/Chart.ts'
export type * from './models/SourceLink.ts'
export type * from './models/Dashboard.ts'
export type * from './models/Slot.ts'
export type * from './commonInputTypes.ts'