
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `OrgProject` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model OrgProject
 * 
 */
export type OrgProjectModel = runtime.Types.Result.DefaultSelection<Prisma.$OrgProjectPayload>

export type AggregateOrgProject = {
  _count: OrgProjectCountAggregateOutputType | null
  _min: OrgProjectMinAggregateOutputType | null
  _max: OrgProjectMaxAggregateOutputType | null
}

export type OrgProjectMinAggregateOutputType = {
  orgId: string | null
  projectId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OrgProjectMaxAggregateOutputType = {
  orgId: string | null
  projectId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OrgProjectCountAggregateOutputType = {
  orgId: number
  projectId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type OrgProjectMinAggregateInputType = {
  orgId?: true
  projectId?: true
  createdAt?: true
  updatedAt?: true
}

export type OrgProjectMaxAggregateInputType = {
  orgId?: true
  projectId?: true
  createdAt?: true
  updatedAt?: true
}

export type OrgProjectCountAggregateInputType = {
  orgId?: true
  projectId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type OrgProjectAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OrgProject to aggregate.
   */
  where?: Prisma.OrgProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrgProjects to fetch.
   */
  orderBy?: Prisma.OrgProjectOrderByWithRelationInput | Prisma.OrgProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.OrgProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrgProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrgProjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned OrgProjects
  **/
  _count?: true | OrgProjectCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OrgProjectMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OrgProjectMaxAggregateInputType
}

export type GetOrgProjectAggregateType<T extends OrgProjectAggregateArgs> = {
      [P in keyof T & keyof AggregateOrgProject]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrgProject[P]>
    : Prisma.GetScalarType<T[P], AggregateOrgProject[P]>
}




export type OrgProjectGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrgProjectWhereInput
  orderBy?: Prisma.OrgProjectOrderByWithAggregationInput | Prisma.OrgProjectOrderByWithAggregationInput[]
  by: Prisma.OrgProjectScalarFieldEnum[] | Prisma.OrgProjectScalarFieldEnum
  having?: Prisma.OrgProjectScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OrgProjectCountAggregateInputType | true
  _min?: OrgProjectMinAggregateInputType
  _max?: OrgProjectMaxAggregateInputType
}

export type OrgProjectGroupByOutputType = {
  orgId: string
  projectId: string
  createdAt: Date
  updatedAt: Date
  _count: OrgProjectCountAggregateOutputType | null
  _min: OrgProjectMinAggregateOutputType | null
  _max: OrgProjectMaxAggregateOutputType | null
}

type GetOrgProjectGroupByPayload<T extends OrgProjectGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OrgProjectGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OrgProjectGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OrgProjectGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OrgProjectGroupByOutputType[P]>
      }
    >
  >



export type OrgProjectWhereInput = {
  AND?: Prisma.OrgProjectWhereInput | Prisma.OrgProjectWhereInput[]
  OR?: Prisma.OrgProjectWhereInput[]
  NOT?: Prisma.OrgProjectWhereInput | Prisma.OrgProjectWhereInput[]
  orgId?: Prisma.StringFilter<"OrgProject"> | string
  projectId?: Prisma.StringFilter<"OrgProject"> | string
  createdAt?: Prisma.DateTimeFilter<"OrgProject"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OrgProject"> | Date | string
  org?: Prisma.XOR<Prisma.OrgScalarRelationFilter, Prisma.OrgWhereInput>
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
}

export type OrgProjectOrderByWithRelationInput = {
  orgId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  org?: Prisma.OrgOrderByWithRelationInput
  project?: Prisma.ProjectOrderByWithRelationInput
}

export type OrgProjectWhereUniqueInput = Prisma.AtLeast<{
  orgId_projectId?: Prisma.OrgProjectOrgIdProjectIdCompoundUniqueInput
  AND?: Prisma.OrgProjectWhereInput | Prisma.OrgProjectWhereInput[]
  OR?: Prisma.OrgProjectWhereInput[]
  NOT?: Prisma.OrgProjectWhereInput | Prisma.OrgProjectWhereInput[]
  orgId?: Prisma.StringFilter<"OrgProject"> | string
  projectId?: Prisma.StringFilter<"OrgProject"> | string
  createdAt?: Prisma.DateTimeFilter<"OrgProject"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OrgProject"> | Date | string
  org?: Prisma.XOR<Prisma.OrgScalarRelationFilter, Prisma.OrgWhereInput>
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
}, "orgId_projectId">

export type OrgProjectOrderByWithAggregationInput = {
  orgId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.OrgProjectCountOrderByAggregateInput
  _max?: Prisma.OrgProjectMaxOrderByAggregateInput
  _min?: Prisma.OrgProjectMinOrderByAggregateInput
}

export type OrgProjectScalarWhereWithAggregatesInput = {
  AND?: Prisma.OrgProjectScalarWhereWithAggregatesInput | Prisma.OrgProjectScalarWhereWithAggregatesInput[]
  OR?: Prisma.OrgProjectScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OrgProjectScalarWhereWithAggregatesInput | Prisma.OrgProjectScalarWhereWithAggregatesInput[]
  orgId?: Prisma.StringWithAggregatesFilter<"OrgProject"> | string
  projectId?: Prisma.StringWithAggregatesFilter<"OrgProject"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"OrgProject"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"OrgProject"> | Date | string
}

export type OrgProjectCreateInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  org: Prisma.OrgCreateNestedOneWithoutProjectsInput
  project: Prisma.ProjectCreateNestedOneWithoutOrgsInput
}

export type OrgProjectUncheckedCreateInput = {
  orgId: string
  projectId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrgProjectUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  org?: Prisma.OrgUpdateOneRequiredWithoutProjectsNestedInput
  project?: Prisma.ProjectUpdateOneRequiredWithoutOrgsNestedInput
}

export type OrgProjectUncheckedUpdateInput = {
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrgProjectCreateManyInput = {
  orgId: string
  projectId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrgProjectUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrgProjectUncheckedUpdateManyInput = {
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrgProjectListRelationFilter = {
  every?: Prisma.OrgProjectWhereInput
  some?: Prisma.OrgProjectWhereInput
  none?: Prisma.OrgProjectWhereInput
}

export type OrgProjectOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type OrgProjectOrgIdProjectIdCompoundUniqueInput = {
  orgId: string
  projectId: string
}

export type OrgProjectCountOrderByAggregateInput = {
  orgId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OrgProjectMaxOrderByAggregateInput = {
  orgId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OrgProjectMinOrderByAggregateInput = {
  orgId?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OrgProjectCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.OrgProjectCreateWithoutProjectInput, Prisma.OrgProjectUncheckedCreateWithoutProjectInput> | Prisma.OrgProjectCreateWithoutProjectInput[] | Prisma.OrgProjectUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.OrgProjectCreateOrConnectWithoutProjectInput | Prisma.OrgProjectCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.OrgProjectCreateManyProjectInputEnvelope
  connect?: Prisma.OrgProjectWhereUniqueInput | Prisma.OrgProjectWhereUniqueInput[]
}

export type OrgProjectUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.OrgProjectCreateWithoutProjectInput, Prisma.OrgProjectUncheckedCreateWithoutProjectInput> | Prisma.OrgProjectCreateWithoutProjectInput[] | Prisma.OrgProjectUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.OrgProjectCreateOrConnectWithoutProjectInput | Prisma.OrgProjectCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.OrgProjectCreateManyProjectInputEnvelope
  connect?: Prisma.OrgProjectWhereUniqueInput | Prisma.OrgProjectWhereUniqueInput[]
}

export type OrgProjectUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.OrgProjectCreateWithoutProjectInput, Prisma.OrgProjectUncheckedCreateWithoutProjectInput> | Prisma.OrgProjectCreateWithoutProjectInput[] | Prisma.OrgProjectUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.OrgProjectCreateOrConnectWithoutProjectInput | Prisma.OrgProjectCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.OrgProjectUpsertWithWhereUniqueWithoutProjectInput | Prisma.OrgProjectUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.OrgProjectCreateManyProjectInputEnvelope
  set?: Prisma.OrgProjectWhereUniqueInput | Prisma.OrgProjectWhereUniqueInput[]
  disconnect?: Prisma.OrgProjectWhereUniqueInput | Prisma.OrgProjectWhereUniqueInput[]
  delete?: Prisma.OrgProjectWhereUniqueInput | Prisma.OrgProjectWhereUniqueInput[]
  connect?: Prisma.OrgProjectWhereUniqueInput | Prisma.OrgProjectWhereUniqueInput[]
  update?: Prisma.OrgProjectUpdateWithWhereUniqueWithoutProjectInput | Prisma.OrgProjectUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.OrgProjectUpdateManyWithWhereWithoutProjectInput | Prisma.OrgProjectUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.OrgProjectScalarWhereInput | Prisma.OrgProjectScalarWhereInput[]
}

export type OrgProjectUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.OrgProjectCreateWithoutProjectInput, Prisma.OrgProjectUncheckedCreateWithoutProjectInput> | Prisma.OrgProjectCreateWithoutProjectInput[] | Prisma.OrgProjectUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.OrgProjectCreateOrConnectWithoutProjectInput | Prisma.OrgProjectCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.OrgProjectUpsertWithWhereUniqueWithoutProjectInput | Prisma.OrgProjectUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.OrgProjectCreateManyProjectInputEnvelope
  set?: Prisma.OrgProjectWhereUniqueInput | Prisma.OrgProjectWhereUniqueInput[]
  disconnect?: Prisma.OrgProjectWhereUniqueInput | Prisma.OrgProjectWhereUniqueInput[]
  delete?: Prisma.OrgProjectWhereUniqueInput | Prisma.OrgProjectWhereUniqueInput[]
  connect?: Prisma.OrgProjectWhereUniqueInput | Prisma.OrgProjectWhereUniqueInput[]
  update?: Prisma.OrgProjectUpdateWithWhereUniqueWithoutProjectInput | Prisma.OrgProjectUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.OrgProjectUpdateManyWithWhereWithoutProjectInput | Prisma.OrgProjectUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.OrgProjectScalarWhereInput | Prisma.OrgProjectScalarWhereInput[]
}

export type OrgProjectCreateNestedManyWithoutOrgInput = {
  create?: Prisma.XOR<Prisma.OrgProjectCreateWithoutOrgInput, Prisma.OrgProjectUncheckedCreateWithoutOrgInput> | Prisma.OrgProjectCreateWithoutOrgInput[] | Prisma.OrgProjectUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.OrgProjectCreateOrConnectWithoutOrgInput | Prisma.OrgProjectCreateOrConnectWithoutOrgInput[]
  createMany?: Prisma.OrgProjectCreateManyOrgInputEnvelope
  connect?: Prisma.OrgProjectWhereUniqueInput | Prisma.OrgProjectWhereUniqueInput[]
}

export type OrgProjectUncheckedCreateNestedManyWithoutOrgInput = {
  create?: Prisma.XOR<Prisma.OrgProjectCreateWithoutOrgInput, Prisma.OrgProjectUncheckedCreateWithoutOrgInput> | Prisma.OrgProjectCreateWithoutOrgInput[] | Prisma.OrgProjectUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.OrgProjectCreateOrConnectWithoutOrgInput | Prisma.OrgProjectCreateOrConnectWithoutOrgInput[]
  createMany?: Prisma.OrgProjectCreateManyOrgInputEnvelope
  connect?: Prisma.OrgProjectWhereUniqueInput | Prisma.OrgProjectWhereUniqueInput[]
}

export type OrgProjectUpdateManyWithoutOrgNestedInput = {
  create?: Prisma.XOR<Prisma.OrgProjectCreateWithoutOrgInput, Prisma.OrgProjectUncheckedCreateWithoutOrgInput> | Prisma.OrgProjectCreateWithoutOrgInput[] | Prisma.OrgProjectUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.OrgProjectCreateOrConnectWithoutOrgInput | Prisma.OrgProjectCreateOrConnectWithoutOrgInput[]
  upsert?: Prisma.OrgProjectUpsertWithWhereUniqueWithoutOrgInput | Prisma.OrgProjectUpsertWithWhereUniqueWithoutOrgInput[]
  createMany?: Prisma.OrgProjectCreateManyOrgInputEnvelope
  set?: Prisma.OrgProjectWhereUniqueInput | Prisma.OrgProjectWhereUniqueInput[]
  disconnect?: Prisma.OrgProjectWhereUniqueInput | Prisma.OrgProjectWhereUniqueInput[]
  delete?: Prisma.OrgProjectWhereUniqueInput | Prisma.OrgProjectWhereUniqueInput[]
  connect?: Prisma.OrgProjectWhereUniqueInput | Prisma.OrgProjectWhereUniqueInput[]
  update?: Prisma.OrgProjectUpdateWithWhereUniqueWithoutOrgInput | Prisma.OrgProjectUpdateWithWhereUniqueWithoutOrgInput[]
  updateMany?: Prisma.OrgProjectUpdateManyWithWhereWithoutOrgInput | Prisma.OrgProjectUpdateManyWithWhereWithoutOrgInput[]
  deleteMany?: Prisma.OrgProjectScalarWhereInput | Prisma.OrgProjectScalarWhereInput[]
}

export type OrgProjectUncheckedUpdateManyWithoutOrgNestedInput = {
  create?: Prisma.XOR<Prisma.OrgProjectCreateWithoutOrgInput, Prisma.OrgProjectUncheckedCreateWithoutOrgInput> | Prisma.OrgProjectCreateWithoutOrgInput[] | Prisma.OrgProjectUncheckedCreateWithoutOrgInput[]
  connectOrCreate?: Prisma.OrgProjectCreateOrConnectWithoutOrgInput | Prisma.OrgProjectCreateOrConnectWithoutOrgInput[]
  upsert?: Prisma.OrgProjectUpsertWithWhereUniqueWithoutOrgInput | Prisma.OrgProjectUpsertWithWhereUniqueWithoutOrgInput[]
  createMany?: Prisma.OrgProjectCreateManyOrgInputEnvelope
  set?: Prisma.OrgProjectWhereUniqueInput | Prisma.OrgProjectWhereUniqueInput[]
  disconnect?: Prisma.OrgProjectWhereUniqueInput | Prisma.OrgProjectWhereUniqueInput[]
  delete?: Prisma.OrgProjectWhereUniqueInput | Prisma.OrgProjectWhereUniqueInput[]
  connect?: Prisma.OrgProjectWhereUniqueInput | Prisma.OrgProjectWhereUniqueInput[]
  update?: Prisma.OrgProjectUpdateWithWhereUniqueWithoutOrgInput | Prisma.OrgProjectUpdateWithWhereUniqueWithoutOrgInput[]
  updateMany?: Prisma.OrgProjectUpdateManyWithWhereWithoutOrgInput | Prisma.OrgProjectUpdateManyWithWhereWithoutOrgInput[]
  deleteMany?: Prisma.OrgProjectScalarWhereInput | Prisma.OrgProjectScalarWhereInput[]
}

export type OrgProjectCreateWithoutProjectInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  org: Prisma.OrgCreateNestedOneWithoutProjectsInput
}

export type OrgProjectUncheckedCreateWithoutProjectInput = {
  orgId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrgProjectCreateOrConnectWithoutProjectInput = {
  where: Prisma.OrgProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.OrgProjectCreateWithoutProjectInput, Prisma.OrgProjectUncheckedCreateWithoutProjectInput>
}

export type OrgProjectCreateManyProjectInputEnvelope = {
  data: Prisma.OrgProjectCreateManyProjectInput | Prisma.OrgProjectCreateManyProjectInput[]
  skipDuplicates?: boolean
}

export type OrgProjectUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.OrgProjectWhereUniqueInput
  update: Prisma.XOR<Prisma.OrgProjectUpdateWithoutProjectInput, Prisma.OrgProjectUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.OrgProjectCreateWithoutProjectInput, Prisma.OrgProjectUncheckedCreateWithoutProjectInput>
}

export type OrgProjectUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.OrgProjectWhereUniqueInput
  data: Prisma.XOR<Prisma.OrgProjectUpdateWithoutProjectInput, Prisma.OrgProjectUncheckedUpdateWithoutProjectInput>
}

export type OrgProjectUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.OrgProjectScalarWhereInput
  data: Prisma.XOR<Prisma.OrgProjectUpdateManyMutationInput, Prisma.OrgProjectUncheckedUpdateManyWithoutProjectInput>
}

export type OrgProjectScalarWhereInput = {
  AND?: Prisma.OrgProjectScalarWhereInput | Prisma.OrgProjectScalarWhereInput[]
  OR?: Prisma.OrgProjectScalarWhereInput[]
  NOT?: Prisma.OrgProjectScalarWhereInput | Prisma.OrgProjectScalarWhereInput[]
  orgId?: Prisma.StringFilter<"OrgProject"> | string
  projectId?: Prisma.StringFilter<"OrgProject"> | string
  createdAt?: Prisma.DateTimeFilter<"OrgProject"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OrgProject"> | Date | string
}

export type OrgProjectCreateWithoutOrgInput = {
  createdAt?: Date | string
  updatedAt?: Date | string
  project: Prisma.ProjectCreateNestedOneWithoutOrgsInput
}

export type OrgProjectUncheckedCreateWithoutOrgInput = {
  projectId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrgProjectCreateOrConnectWithoutOrgInput = {
  where: Prisma.OrgProjectWhereUniqueInput
  create: Prisma.XOR<Prisma.OrgProjectCreateWithoutOrgInput, Prisma.OrgProjectUncheckedCreateWithoutOrgInput>
}

export type OrgProjectCreateManyOrgInputEnvelope = {
  data: Prisma.OrgProjectCreateManyOrgInput | Prisma.OrgProjectCreateManyOrgInput[]
  skipDuplicates?: boolean
}

export type OrgProjectUpsertWithWhereUniqueWithoutOrgInput = {
  where: Prisma.OrgProjectWhereUniqueInput
  update: Prisma.XOR<Prisma.OrgProjectUpdateWithoutOrgInput, Prisma.OrgProjectUncheckedUpdateWithoutOrgInput>
  create: Prisma.XOR<Prisma.OrgProjectCreateWithoutOrgInput, Prisma.OrgProjectUncheckedCreateWithoutOrgInput>
}

export type OrgProjectUpdateWithWhereUniqueWithoutOrgInput = {
  where: Prisma.OrgProjectWhereUniqueInput
  data: Prisma.XOR<Prisma.OrgProjectUpdateWithoutOrgInput, Prisma.OrgProjectUncheckedUpdateWithoutOrgInput>
}

export type OrgProjectUpdateManyWithWhereWithoutOrgInput = {
  where: Prisma.OrgProjectScalarWhereInput
  data: Prisma.XOR<Prisma.OrgProjectUpdateManyMutationInput, Prisma.OrgProjectUncheckedUpdateManyWithoutOrgInput>
}

export type OrgProjectCreateManyProjectInput = {
  orgId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrgProjectUpdateWithoutProjectInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  org?: Prisma.OrgUpdateOneRequiredWithoutProjectsNestedInput
}

export type OrgProjectUncheckedUpdateWithoutProjectInput = {
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrgProjectUncheckedUpdateManyWithoutProjectInput = {
  orgId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrgProjectCreateManyOrgInput = {
  projectId: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrgProjectUpdateWithoutOrgInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  project?: Prisma.ProjectUpdateOneRequiredWithoutOrgsNestedInput
}

export type OrgProjectUncheckedUpdateWithoutOrgInput = {
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrgProjectUncheckedUpdateManyWithoutOrgInput = {
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type OrgProjectSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  orgId?: boolean
  projectId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["orgProject"]>

export type OrgProjectSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  orgId?: boolean
  projectId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["orgProject"]>

export type OrgProjectSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  orgId?: boolean
  projectId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["orgProject"]>

export type OrgProjectSelectScalar = {
  orgId?: boolean
  projectId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type OrgProjectOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"orgId" | "projectId" | "createdAt" | "updatedAt", ExtArgs["result"]["orgProject"]>
export type OrgProjectInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type OrgProjectIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type OrgProjectIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  org?: boolean | Prisma.OrgDefaultArgs<ExtArgs>
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}

export type $OrgProjectPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "OrgProject"
  objects: {
    org: Prisma.$OrgPayload<ExtArgs>
    project: Prisma.$ProjectPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    orgId: string
    projectId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["orgProject"]>
  composites: {}
}

export type OrgProjectGetPayload<S extends boolean | null | undefined | OrgProjectDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OrgProjectPayload, S>

export type OrgProjectCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OrgProjectFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OrgProjectCountAggregateInputType | true
  }

export interface OrgProjectDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['OrgProject'], meta: { name: 'OrgProject' } }
  /**
   * Find zero or one OrgProject that matches the filter.
   * @param {OrgProjectFindUniqueArgs} args - Arguments to find a OrgProject
   * @example
   * // Get one OrgProject
   * const orgProject = await prisma.orgProject.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OrgProjectFindUniqueArgs>(args: Prisma.SelectSubset<T, OrgProjectFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OrgProjectClient<runtime.Types.Result.GetResult<Prisma.$OrgProjectPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OrgProject that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OrgProjectFindUniqueOrThrowArgs} args - Arguments to find a OrgProject
   * @example
   * // Get one OrgProject
   * const orgProject = await prisma.orgProject.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OrgProjectFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OrgProjectFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrgProjectClient<runtime.Types.Result.GetResult<Prisma.$OrgProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrgProject that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrgProjectFindFirstArgs} args - Arguments to find a OrgProject
   * @example
   * // Get one OrgProject
   * const orgProject = await prisma.orgProject.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OrgProjectFindFirstArgs>(args?: Prisma.SelectSubset<T, OrgProjectFindFirstArgs<ExtArgs>>): Prisma.Prisma__OrgProjectClient<runtime.Types.Result.GetResult<Prisma.$OrgProjectPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrgProject that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrgProjectFindFirstOrThrowArgs} args - Arguments to find a OrgProject
   * @example
   * // Get one OrgProject
   * const orgProject = await prisma.orgProject.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OrgProjectFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OrgProjectFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrgProjectClient<runtime.Types.Result.GetResult<Prisma.$OrgProjectPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OrgProjects that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrgProjectFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OrgProjects
   * const orgProjects = await prisma.orgProject.findMany()
   * 
   * // Get first 10 OrgProjects
   * const orgProjects = await prisma.orgProject.findMany({ take: 10 })
   * 
   * // Only select the `orgId`
   * const orgProjectWithOrgIdOnly = await prisma.orgProject.findMany({ select: { orgId: true } })
   * 
   */
  findMany<T extends OrgProjectFindManyArgs>(args?: Prisma.SelectSubset<T, OrgProjectFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrgProjectPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OrgProject.
   * @param {OrgProjectCreateArgs} args - Arguments to create a OrgProject.
   * @example
   * // Create one OrgProject
   * const OrgProject = await prisma.orgProject.create({
   *   data: {
   *     // ... data to create a OrgProject
   *   }
   * })
   * 
   */
  create<T extends OrgProjectCreateArgs>(args: Prisma.SelectSubset<T, OrgProjectCreateArgs<ExtArgs>>): Prisma.Prisma__OrgProjectClient<runtime.Types.Result.GetResult<Prisma.$OrgProjectPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OrgProjects.
   * @param {OrgProjectCreateManyArgs} args - Arguments to create many OrgProjects.
   * @example
   * // Create many OrgProjects
   * const orgProject = await prisma.orgProject.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends OrgProjectCreateManyArgs>(args?: Prisma.SelectSubset<T, OrgProjectCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many OrgProjects and returns the data saved in the database.
   * @param {OrgProjectCreateManyAndReturnArgs} args - Arguments to create many OrgProjects.
   * @example
   * // Create many OrgProjects
   * const orgProject = await prisma.orgProject.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many OrgProjects and only return the `orgId`
   * const orgProjectWithOrgIdOnly = await prisma.orgProject.createManyAndReturn({
   *   select: { orgId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends OrgProjectCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, OrgProjectCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrgProjectPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a OrgProject.
   * @param {OrgProjectDeleteArgs} args - Arguments to delete one OrgProject.
   * @example
   * // Delete one OrgProject
   * const OrgProject = await prisma.orgProject.delete({
   *   where: {
   *     // ... filter to delete one OrgProject
   *   }
   * })
   * 
   */
  delete<T extends OrgProjectDeleteArgs>(args: Prisma.SelectSubset<T, OrgProjectDeleteArgs<ExtArgs>>): Prisma.Prisma__OrgProjectClient<runtime.Types.Result.GetResult<Prisma.$OrgProjectPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OrgProject.
   * @param {OrgProjectUpdateArgs} args - Arguments to update one OrgProject.
   * @example
   * // Update one OrgProject
   * const orgProject = await prisma.orgProject.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends OrgProjectUpdateArgs>(args: Prisma.SelectSubset<T, OrgProjectUpdateArgs<ExtArgs>>): Prisma.Prisma__OrgProjectClient<runtime.Types.Result.GetResult<Prisma.$OrgProjectPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OrgProjects.
   * @param {OrgProjectDeleteManyArgs} args - Arguments to filter OrgProjects to delete.
   * @example
   * // Delete a few OrgProjects
   * const { count } = await prisma.orgProject.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends OrgProjectDeleteManyArgs>(args?: Prisma.SelectSubset<T, OrgProjectDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OrgProjects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrgProjectUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OrgProjects
   * const orgProject = await prisma.orgProject.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends OrgProjectUpdateManyArgs>(args: Prisma.SelectSubset<T, OrgProjectUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OrgProjects and returns the data updated in the database.
   * @param {OrgProjectUpdateManyAndReturnArgs} args - Arguments to update many OrgProjects.
   * @example
   * // Update many OrgProjects
   * const orgProject = await prisma.orgProject.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more OrgProjects and only return the `orgId`
   * const orgProjectWithOrgIdOnly = await prisma.orgProject.updateManyAndReturn({
   *   select: { orgId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends OrgProjectUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, OrgProjectUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrgProjectPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one OrgProject.
   * @param {OrgProjectUpsertArgs} args - Arguments to update or create a OrgProject.
   * @example
   * // Update or create a OrgProject
   * const orgProject = await prisma.orgProject.upsert({
   *   create: {
   *     // ... data to create a OrgProject
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OrgProject we want to update
   *   }
   * })
   */
  upsert<T extends OrgProjectUpsertArgs>(args: Prisma.SelectSubset<T, OrgProjectUpsertArgs<ExtArgs>>): Prisma.Prisma__OrgProjectClient<runtime.Types.Result.GetResult<Prisma.$OrgProjectPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OrgProjects.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrgProjectCountArgs} args - Arguments to filter OrgProjects to count.
   * @example
   * // Count the number of OrgProjects
   * const count = await prisma.orgProject.count({
   *   where: {
   *     // ... the filter for the OrgProjects we want to count
   *   }
   * })
  **/
  count<T extends OrgProjectCountArgs>(
    args?: Prisma.Subset<T, OrgProjectCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OrgProjectCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OrgProject.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrgProjectAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OrgProjectAggregateArgs>(args: Prisma.Subset<T, OrgProjectAggregateArgs>): Prisma.PrismaPromise<GetOrgProjectAggregateType<T>>

  /**
   * Group by OrgProject.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrgProjectGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends OrgProjectGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OrgProjectGroupByArgs['orderBy'] }
      : { orderBy?: OrgProjectGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OrgProjectGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOrgProjectGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the OrgProject model
 */
readonly fields: OrgProjectFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OrgProject.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OrgProjectClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  org<T extends Prisma.OrgDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrgDefaultArgs<ExtArgs>>): Prisma.Prisma__OrgClient<runtime.Types.Result.GetResult<Prisma.$OrgPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  project<T extends Prisma.ProjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProjectDefaultArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the OrgProject model
 */
export interface OrgProjectFieldRefs {
  readonly orgId: Prisma.FieldRef<"OrgProject", 'String'>
  readonly projectId: Prisma.FieldRef<"OrgProject", 'String'>
  readonly createdAt: Prisma.FieldRef<"OrgProject", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"OrgProject", 'DateTime'>
}
    

// Custom InputTypes
/**
 * OrgProject findUnique
 */
export type OrgProjectFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProject
   */
  select?: Prisma.OrgProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProject
   */
  omit?: Prisma.OrgProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProjectInclude<ExtArgs> | null
  /**
   * Filter, which OrgProject to fetch.
   */
  where: Prisma.OrgProjectWhereUniqueInput
}

/**
 * OrgProject findUniqueOrThrow
 */
export type OrgProjectFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProject
   */
  select?: Prisma.OrgProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProject
   */
  omit?: Prisma.OrgProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProjectInclude<ExtArgs> | null
  /**
   * Filter, which OrgProject to fetch.
   */
  where: Prisma.OrgProjectWhereUniqueInput
}

/**
 * OrgProject findFirst
 */
export type OrgProjectFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProject
   */
  select?: Prisma.OrgProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProject
   */
  omit?: Prisma.OrgProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProjectInclude<ExtArgs> | null
  /**
   * Filter, which OrgProject to fetch.
   */
  where?: Prisma.OrgProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrgProjects to fetch.
   */
  orderBy?: Prisma.OrgProjectOrderByWithRelationInput | Prisma.OrgProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OrgProjects.
   */
  cursor?: Prisma.OrgProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrgProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrgProjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrgProjects.
   */
  distinct?: Prisma.OrgProjectScalarFieldEnum | Prisma.OrgProjectScalarFieldEnum[]
}

/**
 * OrgProject findFirstOrThrow
 */
export type OrgProjectFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProject
   */
  select?: Prisma.OrgProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProject
   */
  omit?: Prisma.OrgProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProjectInclude<ExtArgs> | null
  /**
   * Filter, which OrgProject to fetch.
   */
  where?: Prisma.OrgProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrgProjects to fetch.
   */
  orderBy?: Prisma.OrgProjectOrderByWithRelationInput | Prisma.OrgProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OrgProjects.
   */
  cursor?: Prisma.OrgProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrgProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrgProjects.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrgProjects.
   */
  distinct?: Prisma.OrgProjectScalarFieldEnum | Prisma.OrgProjectScalarFieldEnum[]
}

/**
 * OrgProject findMany
 */
export type OrgProjectFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProject
   */
  select?: Prisma.OrgProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProject
   */
  omit?: Prisma.OrgProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProjectInclude<ExtArgs> | null
  /**
   * Filter, which OrgProjects to fetch.
   */
  where?: Prisma.OrgProjectWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrgProjects to fetch.
   */
  orderBy?: Prisma.OrgProjectOrderByWithRelationInput | Prisma.OrgProjectOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing OrgProjects.
   */
  cursor?: Prisma.OrgProjectWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrgProjects from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrgProjects.
   */
  skip?: number
  distinct?: Prisma.OrgProjectScalarFieldEnum | Prisma.OrgProjectScalarFieldEnum[]
}

/**
 * OrgProject create
 */
export type OrgProjectCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProject
   */
  select?: Prisma.OrgProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProject
   */
  omit?: Prisma.OrgProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProjectInclude<ExtArgs> | null
  /**
   * The data needed to create a OrgProject.
   */
  data: Prisma.XOR<Prisma.OrgProjectCreateInput, Prisma.OrgProjectUncheckedCreateInput>
}

/**
 * OrgProject createMany
 */
export type OrgProjectCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many OrgProjects.
   */
  data: Prisma.OrgProjectCreateManyInput | Prisma.OrgProjectCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OrgProject createManyAndReturn
 */
export type OrgProjectCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProject
   */
  select?: Prisma.OrgProjectSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProject
   */
  omit?: Prisma.OrgProjectOmit<ExtArgs> | null
  /**
   * The data used to create many OrgProjects.
   */
  data: Prisma.OrgProjectCreateManyInput | Prisma.OrgProjectCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProjectIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * OrgProject update
 */
export type OrgProjectUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProject
   */
  select?: Prisma.OrgProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProject
   */
  omit?: Prisma.OrgProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProjectInclude<ExtArgs> | null
  /**
   * The data needed to update a OrgProject.
   */
  data: Prisma.XOR<Prisma.OrgProjectUpdateInput, Prisma.OrgProjectUncheckedUpdateInput>
  /**
   * Choose, which OrgProject to update.
   */
  where: Prisma.OrgProjectWhereUniqueInput
}

/**
 * OrgProject updateMany
 */
export type OrgProjectUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update OrgProjects.
   */
  data: Prisma.XOR<Prisma.OrgProjectUpdateManyMutationInput, Prisma.OrgProjectUncheckedUpdateManyInput>
  /**
   * Filter which OrgProjects to update
   */
  where?: Prisma.OrgProjectWhereInput
  /**
   * Limit how many OrgProjects to update.
   */
  limit?: number
}

/**
 * OrgProject updateManyAndReturn
 */
export type OrgProjectUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProject
   */
  select?: Prisma.OrgProjectSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProject
   */
  omit?: Prisma.OrgProjectOmit<ExtArgs> | null
  /**
   * The data used to update OrgProjects.
   */
  data: Prisma.XOR<Prisma.OrgProjectUpdateManyMutationInput, Prisma.OrgProjectUncheckedUpdateManyInput>
  /**
   * Filter which OrgProjects to update
   */
  where?: Prisma.OrgProjectWhereInput
  /**
   * Limit how many OrgProjects to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProjectIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * OrgProject upsert
 */
export type OrgProjectUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProject
   */
  select?: Prisma.OrgProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProject
   */
  omit?: Prisma.OrgProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProjectInclude<ExtArgs> | null
  /**
   * The filter to search for the OrgProject to update in case it exists.
   */
  where: Prisma.OrgProjectWhereUniqueInput
  /**
   * In case the OrgProject found by the `where` argument doesn't exist, create a new OrgProject with this data.
   */
  create: Prisma.XOR<Prisma.OrgProjectCreateInput, Prisma.OrgProjectUncheckedCreateInput>
  /**
   * In case the OrgProject was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OrgProjectUpdateInput, Prisma.OrgProjectUncheckedUpdateInput>
}

/**
 * OrgProject delete
 */
export type OrgProjectDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProject
   */
  select?: Prisma.OrgProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProject
   */
  omit?: Prisma.OrgProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProjectInclude<ExtArgs> | null
  /**
   * Filter which OrgProject to delete.
   */
  where: Prisma.OrgProjectWhereUniqueInput
}

/**
 * OrgProject deleteMany
 */
export type OrgProjectDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OrgProjects to delete
   */
  where?: Prisma.OrgProjectWhereInput
  /**
   * Limit how many OrgProjects to delete.
   */
  limit?: number
}

/**
 * OrgProject without action
 */
export type OrgProjectDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrgProject
   */
  select?: Prisma.OrgProjectSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrgProject
   */
  omit?: Prisma.OrgProjectOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrgProjectInclude<ExtArgs> | null
}
