
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Slot` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Slot
 * 
 */
export type SlotModel = runtime.Types.Result.DefaultSelection<Prisma.$SlotPayload>

export type AggregateSlot = {
  _count: SlotCountAggregateOutputType | null
  _min: SlotMinAggregateOutputType | null
  _max: SlotMaxAggregateOutputType | null
}

export type SlotMinAggregateOutputType = {
  dashboardId: string | null
  chartId: string | null
  name: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SlotMaxAggregateOutputType = {
  dashboardId: string | null
  chartId: string | null
  name: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SlotCountAggregateOutputType = {
  dashboardId: number
  chartId: number
  settings: number
  name: number
  description: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type SlotMinAggregateInputType = {
  dashboardId?: true
  chartId?: true
  name?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type SlotMaxAggregateInputType = {
  dashboardId?: true
  chartId?: true
  name?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type SlotCountAggregateInputType = {
  dashboardId?: true
  chartId?: true
  settings?: true
  name?: true
  description?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type SlotAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Slot to aggregate.
   */
  where?: Prisma.SlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Slots to fetch.
   */
  orderBy?: Prisma.SlotOrderByWithRelationInput | Prisma.SlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Slots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Slots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Slots
  **/
  _count?: true | SlotCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SlotMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SlotMaxAggregateInputType
}

export type GetSlotAggregateType<T extends SlotAggregateArgs> = {
      [P in keyof T & keyof AggregateSlot]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSlot[P]>
    : Prisma.GetScalarType<T[P], AggregateSlot[P]>
}




export type SlotGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SlotWhereInput
  orderBy?: Prisma.SlotOrderByWithAggregationInput | Prisma.SlotOrderByWithAggregationInput[]
  by: Prisma.SlotScalarFieldEnum[] | Prisma.SlotScalarFieldEnum
  having?: Prisma.SlotScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SlotCountAggregateInputType | true
  _min?: SlotMinAggregateInputType
  _max?: SlotMaxAggregateInputType
}

export type SlotGroupByOutputType = {
  dashboardId: string
  chartId: string
  settings: runtime.JsonValue | null
  name: string | null
  description: string | null
  createdAt: Date
  updatedAt: Date
  _count: SlotCountAggregateOutputType | null
  _min: SlotMinAggregateOutputType | null
  _max: SlotMaxAggregateOutputType | null
}

type GetSlotGroupByPayload<T extends SlotGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SlotGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SlotGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SlotGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SlotGroupByOutputType[P]>
      }
    >
  >



export type SlotWhereInput = {
  AND?: Prisma.SlotWhereInput | Prisma.SlotWhereInput[]
  OR?: Prisma.SlotWhereInput[]
  NOT?: Prisma.SlotWhereInput | Prisma.SlotWhereInput[]
  dashboardId?: Prisma.StringFilter<"Slot"> | string
  chartId?: Prisma.StringFilter<"Slot"> | string
  settings?: Prisma.JsonNullableFilter<"Slot">
  name?: Prisma.StringNullableFilter<"Slot"> | string | null
  description?: Prisma.StringNullableFilter<"Slot"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Slot"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Slot"> | Date | string
  dashboard?: Prisma.XOR<Prisma.DashboardScalarRelationFilter, Prisma.DashboardWhereInput>
  chart?: Prisma.XOR<Prisma.ChartScalarRelationFilter, Prisma.ChartWhereInput>
}

export type SlotOrderByWithRelationInput = {
  dashboardId?: Prisma.SortOrder
  chartId?: Prisma.SortOrder
  settings?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  dashboard?: Prisma.DashboardOrderByWithRelationInput
  chart?: Prisma.ChartOrderByWithRelationInput
}

export type SlotWhereUniqueInput = Prisma.AtLeast<{
  dashboardId_chartId?: Prisma.SlotDashboardIdChartIdCompoundUniqueInput
  AND?: Prisma.SlotWhereInput | Prisma.SlotWhereInput[]
  OR?: Prisma.SlotWhereInput[]
  NOT?: Prisma.SlotWhereInput | Prisma.SlotWhereInput[]
  dashboardId?: Prisma.StringFilter<"Slot"> | string
  chartId?: Prisma.StringFilter<"Slot"> | string
  settings?: Prisma.JsonNullableFilter<"Slot">
  name?: Prisma.StringNullableFilter<"Slot"> | string | null
  description?: Prisma.StringNullableFilter<"Slot"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Slot"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Slot"> | Date | string
  dashboard?: Prisma.XOR<Prisma.DashboardScalarRelationFilter, Prisma.DashboardWhereInput>
  chart?: Prisma.XOR<Prisma.ChartScalarRelationFilter, Prisma.ChartWhereInput>
}, "dashboardId_chartId">

export type SlotOrderByWithAggregationInput = {
  dashboardId?: Prisma.SortOrder
  chartId?: Prisma.SortOrder
  settings?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SlotCountOrderByAggregateInput
  _max?: Prisma.SlotMaxOrderByAggregateInput
  _min?: Prisma.SlotMinOrderByAggregateInput
}

export type SlotScalarWhereWithAggregatesInput = {
  AND?: Prisma.SlotScalarWhereWithAggregatesInput | Prisma.SlotScalarWhereWithAggregatesInput[]
  OR?: Prisma.SlotScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SlotScalarWhereWithAggregatesInput | Prisma.SlotScalarWhereWithAggregatesInput[]
  dashboardId?: Prisma.StringWithAggregatesFilter<"Slot"> | string
  chartId?: Prisma.StringWithAggregatesFilter<"Slot"> | string
  settings?: Prisma.JsonNullableWithAggregatesFilter<"Slot">
  name?: Prisma.StringNullableWithAggregatesFilter<"Slot"> | string | null
  description?: Prisma.StringNullableWithAggregatesFilter<"Slot"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Slot"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Slot"> | Date | string
}

export type SlotCreateInput = {
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  name?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  dashboard: Prisma.DashboardCreateNestedOneWithoutSlotsInput
  chart: Prisma.ChartCreateNestedOneWithoutSlotInput
}

export type SlotUncheckedCreateInput = {
  dashboardId: string
  chartId: string
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  name?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SlotUpdateInput = {
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dashboard?: Prisma.DashboardUpdateOneRequiredWithoutSlotsNestedInput
  chart?: Prisma.ChartUpdateOneRequiredWithoutSlotNestedInput
}

export type SlotUncheckedUpdateInput = {
  dashboardId?: Prisma.StringFieldUpdateOperationsInput | string
  chartId?: Prisma.StringFieldUpdateOperationsInput | string
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SlotCreateManyInput = {
  dashboardId: string
  chartId: string
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  name?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SlotUpdateManyMutationInput = {
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SlotUncheckedUpdateManyInput = {
  dashboardId?: Prisma.StringFieldUpdateOperationsInput | string
  chartId?: Prisma.StringFieldUpdateOperationsInput | string
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SlotListRelationFilter = {
  every?: Prisma.SlotWhereInput
  some?: Prisma.SlotWhereInput
  none?: Prisma.SlotWhereInput
}

export type SlotOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SlotDashboardIdChartIdCompoundUniqueInput = {
  dashboardId: string
  chartId: string
}

export type SlotCountOrderByAggregateInput = {
  dashboardId?: Prisma.SortOrder
  chartId?: Prisma.SortOrder
  settings?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SlotMaxOrderByAggregateInput = {
  dashboardId?: Prisma.SortOrder
  chartId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SlotMinOrderByAggregateInput = {
  dashboardId?: Prisma.SortOrder
  chartId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SlotCreateNestedManyWithoutChartInput = {
  create?: Prisma.XOR<Prisma.SlotCreateWithoutChartInput, Prisma.SlotUncheckedCreateWithoutChartInput> | Prisma.SlotCreateWithoutChartInput[] | Prisma.SlotUncheckedCreateWithoutChartInput[]
  connectOrCreate?: Prisma.SlotCreateOrConnectWithoutChartInput | Prisma.SlotCreateOrConnectWithoutChartInput[]
  createMany?: Prisma.SlotCreateManyChartInputEnvelope
  connect?: Prisma.SlotWhereUniqueInput | Prisma.SlotWhereUniqueInput[]
}

export type SlotUncheckedCreateNestedManyWithoutChartInput = {
  create?: Prisma.XOR<Prisma.SlotCreateWithoutChartInput, Prisma.SlotUncheckedCreateWithoutChartInput> | Prisma.SlotCreateWithoutChartInput[] | Prisma.SlotUncheckedCreateWithoutChartInput[]
  connectOrCreate?: Prisma.SlotCreateOrConnectWithoutChartInput | Prisma.SlotCreateOrConnectWithoutChartInput[]
  createMany?: Prisma.SlotCreateManyChartInputEnvelope
  connect?: Prisma.SlotWhereUniqueInput | Prisma.SlotWhereUniqueInput[]
}

export type SlotUpdateManyWithoutChartNestedInput = {
  create?: Prisma.XOR<Prisma.SlotCreateWithoutChartInput, Prisma.SlotUncheckedCreateWithoutChartInput> | Prisma.SlotCreateWithoutChartInput[] | Prisma.SlotUncheckedCreateWithoutChartInput[]
  connectOrCreate?: Prisma.SlotCreateOrConnectWithoutChartInput | Prisma.SlotCreateOrConnectWithoutChartInput[]
  upsert?: Prisma.SlotUpsertWithWhereUniqueWithoutChartInput | Prisma.SlotUpsertWithWhereUniqueWithoutChartInput[]
  createMany?: Prisma.SlotCreateManyChartInputEnvelope
  set?: Prisma.SlotWhereUniqueInput | Prisma.SlotWhereUniqueInput[]
  disconnect?: Prisma.SlotWhereUniqueInput | Prisma.SlotWhereUniqueInput[]
  delete?: Prisma.SlotWhereUniqueInput | Prisma.SlotWhereUniqueInput[]
  connect?: Prisma.SlotWhereUniqueInput | Prisma.SlotWhereUniqueInput[]
  update?: Prisma.SlotUpdateWithWhereUniqueWithoutChartInput | Prisma.SlotUpdateWithWhereUniqueWithoutChartInput[]
  updateMany?: Prisma.SlotUpdateManyWithWhereWithoutChartInput | Prisma.SlotUpdateManyWithWhereWithoutChartInput[]
  deleteMany?: Prisma.SlotScalarWhereInput | Prisma.SlotScalarWhereInput[]
}

export type SlotUncheckedUpdateManyWithoutChartNestedInput = {
  create?: Prisma.XOR<Prisma.SlotCreateWithoutChartInput, Prisma.SlotUncheckedCreateWithoutChartInput> | Prisma.SlotCreateWithoutChartInput[] | Prisma.SlotUncheckedCreateWithoutChartInput[]
  connectOrCreate?: Prisma.SlotCreateOrConnectWithoutChartInput | Prisma.SlotCreateOrConnectWithoutChartInput[]
  upsert?: Prisma.SlotUpsertWithWhereUniqueWithoutChartInput | Prisma.SlotUpsertWithWhereUniqueWithoutChartInput[]
  createMany?: Prisma.SlotCreateManyChartInputEnvelope
  set?: Prisma.SlotWhereUniqueInput | Prisma.SlotWhereUniqueInput[]
  disconnect?: Prisma.SlotWhereUniqueInput | Prisma.SlotWhereUniqueInput[]
  delete?: Prisma.SlotWhereUniqueInput | Prisma.SlotWhereUniqueInput[]
  connect?: Prisma.SlotWhereUniqueInput | Prisma.SlotWhereUniqueInput[]
  update?: Prisma.SlotUpdateWithWhereUniqueWithoutChartInput | Prisma.SlotUpdateWithWhereUniqueWithoutChartInput[]
  updateMany?: Prisma.SlotUpdateManyWithWhereWithoutChartInput | Prisma.SlotUpdateManyWithWhereWithoutChartInput[]
  deleteMany?: Prisma.SlotScalarWhereInput | Prisma.SlotScalarWhereInput[]
}

export type SlotCreateNestedManyWithoutDashboardInput = {
  create?: Prisma.XOR<Prisma.SlotCreateWithoutDashboardInput, Prisma.SlotUncheckedCreateWithoutDashboardInput> | Prisma.SlotCreateWithoutDashboardInput[] | Prisma.SlotUncheckedCreateWithoutDashboardInput[]
  connectOrCreate?: Prisma.SlotCreateOrConnectWithoutDashboardInput | Prisma.SlotCreateOrConnectWithoutDashboardInput[]
  createMany?: Prisma.SlotCreateManyDashboardInputEnvelope
  connect?: Prisma.SlotWhereUniqueInput | Prisma.SlotWhereUniqueInput[]
}

export type SlotUncheckedCreateNestedManyWithoutDashboardInput = {
  create?: Prisma.XOR<Prisma.SlotCreateWithoutDashboardInput, Prisma.SlotUncheckedCreateWithoutDashboardInput> | Prisma.SlotCreateWithoutDashboardInput[] | Prisma.SlotUncheckedCreateWithoutDashboardInput[]
  connectOrCreate?: Prisma.SlotCreateOrConnectWithoutDashboardInput | Prisma.SlotCreateOrConnectWithoutDashboardInput[]
  createMany?: Prisma.SlotCreateManyDashboardInputEnvelope
  connect?: Prisma.SlotWhereUniqueInput | Prisma.SlotWhereUniqueInput[]
}

export type SlotUpdateManyWithoutDashboardNestedInput = {
  create?: Prisma.XOR<Prisma.SlotCreateWithoutDashboardInput, Prisma.SlotUncheckedCreateWithoutDashboardInput> | Prisma.SlotCreateWithoutDashboardInput[] | Prisma.SlotUncheckedCreateWithoutDashboardInput[]
  connectOrCreate?: Prisma.SlotCreateOrConnectWithoutDashboardInput | Prisma.SlotCreateOrConnectWithoutDashboardInput[]
  upsert?: Prisma.SlotUpsertWithWhereUniqueWithoutDashboardInput | Prisma.SlotUpsertWithWhereUniqueWithoutDashboardInput[]
  createMany?: Prisma.SlotCreateManyDashboardInputEnvelope
  set?: Prisma.SlotWhereUniqueInput | Prisma.SlotWhereUniqueInput[]
  disconnect?: Prisma.SlotWhereUniqueInput | Prisma.SlotWhereUniqueInput[]
  delete?: Prisma.SlotWhereUniqueInput | Prisma.SlotWhereUniqueInput[]
  connect?: Prisma.SlotWhereUniqueInput | Prisma.SlotWhereUniqueInput[]
  update?: Prisma.SlotUpdateWithWhereUniqueWithoutDashboardInput | Prisma.SlotUpdateWithWhereUniqueWithoutDashboardInput[]
  updateMany?: Prisma.SlotUpdateManyWithWhereWithoutDashboardInput | Prisma.SlotUpdateManyWithWhereWithoutDashboardInput[]
  deleteMany?: Prisma.SlotScalarWhereInput | Prisma.SlotScalarWhereInput[]
}

export type SlotUncheckedUpdateManyWithoutDashboardNestedInput = {
  create?: Prisma.XOR<Prisma.SlotCreateWithoutDashboardInput, Prisma.SlotUncheckedCreateWithoutDashboardInput> | Prisma.SlotCreateWithoutDashboardInput[] | Prisma.SlotUncheckedCreateWithoutDashboardInput[]
  connectOrCreate?: Prisma.SlotCreateOrConnectWithoutDashboardInput | Prisma.SlotCreateOrConnectWithoutDashboardInput[]
  upsert?: Prisma.SlotUpsertWithWhereUniqueWithoutDashboardInput | Prisma.SlotUpsertWithWhereUniqueWithoutDashboardInput[]
  createMany?: Prisma.SlotCreateManyDashboardInputEnvelope
  set?: Prisma.SlotWhereUniqueInput | Prisma.SlotWhereUniqueInput[]
  disconnect?: Prisma.SlotWhereUniqueInput | Prisma.SlotWhereUniqueInput[]
  delete?: Prisma.SlotWhereUniqueInput | Prisma.SlotWhereUniqueInput[]
  connect?: Prisma.SlotWhereUniqueInput | Prisma.SlotWhereUniqueInput[]
  update?: Prisma.SlotUpdateWithWhereUniqueWithoutDashboardInput | Prisma.SlotUpdateWithWhereUniqueWithoutDashboardInput[]
  updateMany?: Prisma.SlotUpdateManyWithWhereWithoutDashboardInput | Prisma.SlotUpdateManyWithWhereWithoutDashboardInput[]
  deleteMany?: Prisma.SlotScalarWhereInput | Prisma.SlotScalarWhereInput[]
}

export type SlotCreateWithoutChartInput = {
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  name?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  dashboard: Prisma.DashboardCreateNestedOneWithoutSlotsInput
}

export type SlotUncheckedCreateWithoutChartInput = {
  dashboardId: string
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  name?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SlotCreateOrConnectWithoutChartInput = {
  where: Prisma.SlotWhereUniqueInput
  create: Prisma.XOR<Prisma.SlotCreateWithoutChartInput, Prisma.SlotUncheckedCreateWithoutChartInput>
}

export type SlotCreateManyChartInputEnvelope = {
  data: Prisma.SlotCreateManyChartInput | Prisma.SlotCreateManyChartInput[]
  skipDuplicates?: boolean
}

export type SlotUpsertWithWhereUniqueWithoutChartInput = {
  where: Prisma.SlotWhereUniqueInput
  update: Prisma.XOR<Prisma.SlotUpdateWithoutChartInput, Prisma.SlotUncheckedUpdateWithoutChartInput>
  create: Prisma.XOR<Prisma.SlotCreateWithoutChartInput, Prisma.SlotUncheckedCreateWithoutChartInput>
}

export type SlotUpdateWithWhereUniqueWithoutChartInput = {
  where: Prisma.SlotWhereUniqueInput
  data: Prisma.XOR<Prisma.SlotUpdateWithoutChartInput, Prisma.SlotUncheckedUpdateWithoutChartInput>
}

export type SlotUpdateManyWithWhereWithoutChartInput = {
  where: Prisma.SlotScalarWhereInput
  data: Prisma.XOR<Prisma.SlotUpdateManyMutationInput, Prisma.SlotUncheckedUpdateManyWithoutChartInput>
}

export type SlotScalarWhereInput = {
  AND?: Prisma.SlotScalarWhereInput | Prisma.SlotScalarWhereInput[]
  OR?: Prisma.SlotScalarWhereInput[]
  NOT?: Prisma.SlotScalarWhereInput | Prisma.SlotScalarWhereInput[]
  dashboardId?: Prisma.StringFilter<"Slot"> | string
  chartId?: Prisma.StringFilter<"Slot"> | string
  settings?: Prisma.JsonNullableFilter<"Slot">
  name?: Prisma.StringNullableFilter<"Slot"> | string | null
  description?: Prisma.StringNullableFilter<"Slot"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Slot"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Slot"> | Date | string
}

export type SlotCreateWithoutDashboardInput = {
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  name?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  chart: Prisma.ChartCreateNestedOneWithoutSlotInput
}

export type SlotUncheckedCreateWithoutDashboardInput = {
  chartId: string
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  name?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SlotCreateOrConnectWithoutDashboardInput = {
  where: Prisma.SlotWhereUniqueInput
  create: Prisma.XOR<Prisma.SlotCreateWithoutDashboardInput, Prisma.SlotUncheckedCreateWithoutDashboardInput>
}

export type SlotCreateManyDashboardInputEnvelope = {
  data: Prisma.SlotCreateManyDashboardInput | Prisma.SlotCreateManyDashboardInput[]
  skipDuplicates?: boolean
}

export type SlotUpsertWithWhereUniqueWithoutDashboardInput = {
  where: Prisma.SlotWhereUniqueInput
  update: Prisma.XOR<Prisma.SlotUpdateWithoutDashboardInput, Prisma.SlotUncheckedUpdateWithoutDashboardInput>
  create: Prisma.XOR<Prisma.SlotCreateWithoutDashboardInput, Prisma.SlotUncheckedCreateWithoutDashboardInput>
}

export type SlotUpdateWithWhereUniqueWithoutDashboardInput = {
  where: Prisma.SlotWhereUniqueInput
  data: Prisma.XOR<Prisma.SlotUpdateWithoutDashboardInput, Prisma.SlotUncheckedUpdateWithoutDashboardInput>
}

export type SlotUpdateManyWithWhereWithoutDashboardInput = {
  where: Prisma.SlotScalarWhereInput
  data: Prisma.XOR<Prisma.SlotUpdateManyMutationInput, Prisma.SlotUncheckedUpdateManyWithoutDashboardInput>
}

export type SlotCreateManyChartInput = {
  dashboardId: string
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  name?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SlotUpdateWithoutChartInput = {
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dashboard?: Prisma.DashboardUpdateOneRequiredWithoutSlotsNestedInput
}

export type SlotUncheckedUpdateWithoutChartInput = {
  dashboardId?: Prisma.StringFieldUpdateOperationsInput | string
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SlotUncheckedUpdateManyWithoutChartInput = {
  dashboardId?: Prisma.StringFieldUpdateOperationsInput | string
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SlotCreateManyDashboardInput = {
  chartId: string
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  name?: string | null
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SlotUpdateWithoutDashboardInput = {
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chart?: Prisma.ChartUpdateOneRequiredWithoutSlotNestedInput
}

export type SlotUncheckedUpdateWithoutDashboardInput = {
  chartId?: Prisma.StringFieldUpdateOperationsInput | string
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SlotUncheckedUpdateManyWithoutDashboardInput = {
  chartId?: Prisma.StringFieldUpdateOperationsInput | string
  settings?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type SlotSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  dashboardId?: boolean
  chartId?: boolean
  settings?: boolean
  name?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  dashboard?: boolean | Prisma.DashboardDefaultArgs<ExtArgs>
  chart?: boolean | Prisma.ChartDefaultArgs<ExtArgs>
}, ExtArgs["result"]["slot"]>

export type SlotSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  dashboardId?: boolean
  chartId?: boolean
  settings?: boolean
  name?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  dashboard?: boolean | Prisma.DashboardDefaultArgs<ExtArgs>
  chart?: boolean | Prisma.ChartDefaultArgs<ExtArgs>
}, ExtArgs["result"]["slot"]>

export type SlotSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  dashboardId?: boolean
  chartId?: boolean
  settings?: boolean
  name?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  dashboard?: boolean | Prisma.DashboardDefaultArgs<ExtArgs>
  chart?: boolean | Prisma.ChartDefaultArgs<ExtArgs>
}, ExtArgs["result"]["slot"]>

export type SlotSelectScalar = {
  dashboardId?: boolean
  chartId?: boolean
  settings?: boolean
  name?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type SlotOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"dashboardId" | "chartId" | "settings" | "name" | "description" | "createdAt" | "updatedAt", ExtArgs["result"]["slot"]>
export type SlotInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dashboard?: boolean | Prisma.DashboardDefaultArgs<ExtArgs>
  chart?: boolean | Prisma.ChartDefaultArgs<ExtArgs>
}
export type SlotIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dashboard?: boolean | Prisma.DashboardDefaultArgs<ExtArgs>
  chart?: boolean | Prisma.ChartDefaultArgs<ExtArgs>
}
export type SlotIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dashboard?: boolean | Prisma.DashboardDefaultArgs<ExtArgs>
  chart?: boolean | Prisma.ChartDefaultArgs<ExtArgs>
}

export type $SlotPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Slot"
  objects: {
    dashboard: Prisma.$DashboardPayload<ExtArgs>
    chart: Prisma.$ChartPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    dashboardId: string
    chartId: string
    settings: runtime.JsonValue | null
    name: string | null
    description: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["slot"]>
  composites: {}
}

export type SlotGetPayload<S extends boolean | null | undefined | SlotDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SlotPayload, S>

export type SlotCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SlotFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SlotCountAggregateInputType | true
  }

export interface SlotDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Slot'], meta: { name: 'Slot' } }
  /**
   * Find zero or one Slot that matches the filter.
   * @param {SlotFindUniqueArgs} args - Arguments to find a Slot
   * @example
   * // Get one Slot
   * const slot = await prisma.slot.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SlotFindUniqueArgs>(args: Prisma.SelectSubset<T, SlotFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SlotClient<runtime.Types.Result.GetResult<Prisma.$SlotPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Slot that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SlotFindUniqueOrThrowArgs} args - Arguments to find a Slot
   * @example
   * // Get one Slot
   * const slot = await prisma.slot.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SlotFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SlotFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SlotClient<runtime.Types.Result.GetResult<Prisma.$SlotPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Slot that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SlotFindFirstArgs} args - Arguments to find a Slot
   * @example
   * // Get one Slot
   * const slot = await prisma.slot.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SlotFindFirstArgs>(args?: Prisma.SelectSubset<T, SlotFindFirstArgs<ExtArgs>>): Prisma.Prisma__SlotClient<runtime.Types.Result.GetResult<Prisma.$SlotPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Slot that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SlotFindFirstOrThrowArgs} args - Arguments to find a Slot
   * @example
   * // Get one Slot
   * const slot = await prisma.slot.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SlotFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SlotFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SlotClient<runtime.Types.Result.GetResult<Prisma.$SlotPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Slots that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SlotFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Slots
   * const slots = await prisma.slot.findMany()
   * 
   * // Get first 10 Slots
   * const slots = await prisma.slot.findMany({ take: 10 })
   * 
   * // Only select the `dashboardId`
   * const slotWithDashboardIdOnly = await prisma.slot.findMany({ select: { dashboardId: true } })
   * 
   */
  findMany<T extends SlotFindManyArgs>(args?: Prisma.SelectSubset<T, SlotFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SlotPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Slot.
   * @param {SlotCreateArgs} args - Arguments to create a Slot.
   * @example
   * // Create one Slot
   * const Slot = await prisma.slot.create({
   *   data: {
   *     // ... data to create a Slot
   *   }
   * })
   * 
   */
  create<T extends SlotCreateArgs>(args: Prisma.SelectSubset<T, SlotCreateArgs<ExtArgs>>): Prisma.Prisma__SlotClient<runtime.Types.Result.GetResult<Prisma.$SlotPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Slots.
   * @param {SlotCreateManyArgs} args - Arguments to create many Slots.
   * @example
   * // Create many Slots
   * const slot = await prisma.slot.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SlotCreateManyArgs>(args?: Prisma.SelectSubset<T, SlotCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Slots and returns the data saved in the database.
   * @param {SlotCreateManyAndReturnArgs} args - Arguments to create many Slots.
   * @example
   * // Create many Slots
   * const slot = await prisma.slot.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Slots and only return the `dashboardId`
   * const slotWithDashboardIdOnly = await prisma.slot.createManyAndReturn({
   *   select: { dashboardId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SlotCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SlotCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SlotPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Slot.
   * @param {SlotDeleteArgs} args - Arguments to delete one Slot.
   * @example
   * // Delete one Slot
   * const Slot = await prisma.slot.delete({
   *   where: {
   *     // ... filter to delete one Slot
   *   }
   * })
   * 
   */
  delete<T extends SlotDeleteArgs>(args: Prisma.SelectSubset<T, SlotDeleteArgs<ExtArgs>>): Prisma.Prisma__SlotClient<runtime.Types.Result.GetResult<Prisma.$SlotPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Slot.
   * @param {SlotUpdateArgs} args - Arguments to update one Slot.
   * @example
   * // Update one Slot
   * const slot = await prisma.slot.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SlotUpdateArgs>(args: Prisma.SelectSubset<T, SlotUpdateArgs<ExtArgs>>): Prisma.Prisma__SlotClient<runtime.Types.Result.GetResult<Prisma.$SlotPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Slots.
   * @param {SlotDeleteManyArgs} args - Arguments to filter Slots to delete.
   * @example
   * // Delete a few Slots
   * const { count } = await prisma.slot.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SlotDeleteManyArgs>(args?: Prisma.SelectSubset<T, SlotDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Slots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SlotUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Slots
   * const slot = await prisma.slot.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SlotUpdateManyArgs>(args: Prisma.SelectSubset<T, SlotUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Slots and returns the data updated in the database.
   * @param {SlotUpdateManyAndReturnArgs} args - Arguments to update many Slots.
   * @example
   * // Update many Slots
   * const slot = await prisma.slot.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Slots and only return the `dashboardId`
   * const slotWithDashboardIdOnly = await prisma.slot.updateManyAndReturn({
   *   select: { dashboardId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SlotUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SlotUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SlotPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Slot.
   * @param {SlotUpsertArgs} args - Arguments to update or create a Slot.
   * @example
   * // Update or create a Slot
   * const slot = await prisma.slot.upsert({
   *   create: {
   *     // ... data to create a Slot
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Slot we want to update
   *   }
   * })
   */
  upsert<T extends SlotUpsertArgs>(args: Prisma.SelectSubset<T, SlotUpsertArgs<ExtArgs>>): Prisma.Prisma__SlotClient<runtime.Types.Result.GetResult<Prisma.$SlotPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Slots.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SlotCountArgs} args - Arguments to filter Slots to count.
   * @example
   * // Count the number of Slots
   * const count = await prisma.slot.count({
   *   where: {
   *     // ... the filter for the Slots we want to count
   *   }
   * })
  **/
  count<T extends SlotCountArgs>(
    args?: Prisma.Subset<T, SlotCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SlotCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Slot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SlotAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SlotAggregateArgs>(args: Prisma.Subset<T, SlotAggregateArgs>): Prisma.PrismaPromise<GetSlotAggregateType<T>>

  /**
   * Group by Slot.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SlotGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SlotGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SlotGroupByArgs['orderBy'] }
      : { orderBy?: SlotGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SlotGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSlotGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Slot model
 */
readonly fields: SlotFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Slot.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SlotClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  dashboard<T extends Prisma.DashboardDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DashboardDefaultArgs<ExtArgs>>): Prisma.Prisma__DashboardClient<runtime.Types.Result.GetResult<Prisma.$DashboardPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  chart<T extends Prisma.ChartDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ChartDefaultArgs<ExtArgs>>): Prisma.Prisma__ChartClient<runtime.Types.Result.GetResult<Prisma.$ChartPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Slot model
 */
export interface SlotFieldRefs {
  readonly dashboardId: Prisma.FieldRef<"Slot", 'String'>
  readonly chartId: Prisma.FieldRef<"Slot", 'String'>
  readonly settings: Prisma.FieldRef<"Slot", 'Json'>
  readonly name: Prisma.FieldRef<"Slot", 'String'>
  readonly description: Prisma.FieldRef<"Slot", 'String'>
  readonly createdAt: Prisma.FieldRef<"Slot", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Slot", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Slot findUnique
 */
export type SlotFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slot
   */
  select?: Prisma.SlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Slot
   */
  omit?: Prisma.SlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SlotInclude<ExtArgs> | null
  /**
   * Filter, which Slot to fetch.
   */
  where: Prisma.SlotWhereUniqueInput
}

/**
 * Slot findUniqueOrThrow
 */
export type SlotFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slot
   */
  select?: Prisma.SlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Slot
   */
  omit?: Prisma.SlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SlotInclude<ExtArgs> | null
  /**
   * Filter, which Slot to fetch.
   */
  where: Prisma.SlotWhereUniqueInput
}

/**
 * Slot findFirst
 */
export type SlotFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slot
   */
  select?: Prisma.SlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Slot
   */
  omit?: Prisma.SlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SlotInclude<ExtArgs> | null
  /**
   * Filter, which Slot to fetch.
   */
  where?: Prisma.SlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Slots to fetch.
   */
  orderBy?: Prisma.SlotOrderByWithRelationInput | Prisma.SlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Slots.
   */
  cursor?: Prisma.SlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Slots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Slots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Slots.
   */
  distinct?: Prisma.SlotScalarFieldEnum | Prisma.SlotScalarFieldEnum[]
}

/**
 * Slot findFirstOrThrow
 */
export type SlotFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slot
   */
  select?: Prisma.SlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Slot
   */
  omit?: Prisma.SlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SlotInclude<ExtArgs> | null
  /**
   * Filter, which Slot to fetch.
   */
  where?: Prisma.SlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Slots to fetch.
   */
  orderBy?: Prisma.SlotOrderByWithRelationInput | Prisma.SlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Slots.
   */
  cursor?: Prisma.SlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Slots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Slots.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Slots.
   */
  distinct?: Prisma.SlotScalarFieldEnum | Prisma.SlotScalarFieldEnum[]
}

/**
 * Slot findMany
 */
export type SlotFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slot
   */
  select?: Prisma.SlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Slot
   */
  omit?: Prisma.SlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SlotInclude<ExtArgs> | null
  /**
   * Filter, which Slots to fetch.
   */
  where?: Prisma.SlotWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Slots to fetch.
   */
  orderBy?: Prisma.SlotOrderByWithRelationInput | Prisma.SlotOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Slots.
   */
  cursor?: Prisma.SlotWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Slots from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Slots.
   */
  skip?: number
  distinct?: Prisma.SlotScalarFieldEnum | Prisma.SlotScalarFieldEnum[]
}

/**
 * Slot create
 */
export type SlotCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slot
   */
  select?: Prisma.SlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Slot
   */
  omit?: Prisma.SlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SlotInclude<ExtArgs> | null
  /**
   * The data needed to create a Slot.
   */
  data: Prisma.XOR<Prisma.SlotCreateInput, Prisma.SlotUncheckedCreateInput>
}

/**
 * Slot createMany
 */
export type SlotCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Slots.
   */
  data: Prisma.SlotCreateManyInput | Prisma.SlotCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Slot createManyAndReturn
 */
export type SlotCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slot
   */
  select?: Prisma.SlotSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Slot
   */
  omit?: Prisma.SlotOmit<ExtArgs> | null
  /**
   * The data used to create many Slots.
   */
  data: Prisma.SlotCreateManyInput | Prisma.SlotCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SlotIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Slot update
 */
export type SlotUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slot
   */
  select?: Prisma.SlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Slot
   */
  omit?: Prisma.SlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SlotInclude<ExtArgs> | null
  /**
   * The data needed to update a Slot.
   */
  data: Prisma.XOR<Prisma.SlotUpdateInput, Prisma.SlotUncheckedUpdateInput>
  /**
   * Choose, which Slot to update.
   */
  where: Prisma.SlotWhereUniqueInput
}

/**
 * Slot updateMany
 */
export type SlotUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Slots.
   */
  data: Prisma.XOR<Prisma.SlotUpdateManyMutationInput, Prisma.SlotUncheckedUpdateManyInput>
  /**
   * Filter which Slots to update
   */
  where?: Prisma.SlotWhereInput
  /**
   * Limit how many Slots to update.
   */
  limit?: number
}

/**
 * Slot updateManyAndReturn
 */
export type SlotUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slot
   */
  select?: Prisma.SlotSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Slot
   */
  omit?: Prisma.SlotOmit<ExtArgs> | null
  /**
   * The data used to update Slots.
   */
  data: Prisma.XOR<Prisma.SlotUpdateManyMutationInput, Prisma.SlotUncheckedUpdateManyInput>
  /**
   * Filter which Slots to update
   */
  where?: Prisma.SlotWhereInput
  /**
   * Limit how many Slots to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SlotIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Slot upsert
 */
export type SlotUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slot
   */
  select?: Prisma.SlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Slot
   */
  omit?: Prisma.SlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SlotInclude<ExtArgs> | null
  /**
   * The filter to search for the Slot to update in case it exists.
   */
  where: Prisma.SlotWhereUniqueInput
  /**
   * In case the Slot found by the `where` argument doesn't exist, create a new Slot with this data.
   */
  create: Prisma.XOR<Prisma.SlotCreateInput, Prisma.SlotUncheckedCreateInput>
  /**
   * In case the Slot was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SlotUpdateInput, Prisma.SlotUncheckedUpdateInput>
}

/**
 * Slot delete
 */
export type SlotDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slot
   */
  select?: Prisma.SlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Slot
   */
  omit?: Prisma.SlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SlotInclude<ExtArgs> | null
  /**
   * Filter which Slot to delete.
   */
  where: Prisma.SlotWhereUniqueInput
}

/**
 * Slot deleteMany
 */
export type SlotDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Slots to delete
   */
  where?: Prisma.SlotWhereInput
  /**
   * Limit how many Slots to delete.
   */
  limit?: number
}

/**
 * Slot without action
 */
export type SlotDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Slot
   */
  select?: Prisma.SlotSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Slot
   */
  omit?: Prisma.SlotOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SlotInclude<ExtArgs> | null
}
