
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SourceLink` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model SourceLink
 * 
 */
export type SourceLinkModel = runtime.Types.Result.DefaultSelection<Prisma.$SourceLinkPayload>

export type AggregateSourceLink = {
  _count: SourceLinkCountAggregateOutputType | null
  _min: SourceLinkMinAggregateOutputType | null
  _max: SourceLinkMaxAggregateOutputType | null
}

export type SourceLinkMinAggregateOutputType = {
  dataSourceId: string | null
  chartId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SourceLinkMaxAggregateOutputType = {
  dataSourceId: string | null
  chartId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SourceLinkCountAggregateOutputType = {
  dataSourceId: number
  chartId: number
  config: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type SourceLinkMinAggregateInputType = {
  dataSourceId?: true
  chartId?: true
  createdAt?: true
  updatedAt?: true
}

export type SourceLinkMaxAggregateInputType = {
  dataSourceId?: true
  chartId?: true
  createdAt?: true
  updatedAt?: true
}

export type SourceLinkCountAggregateInputType = {
  dataSourceId?: true
  chartId?: true
  config?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type SourceLinkAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SourceLink to aggregate.
   */
  where?: Prisma.SourceLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SourceLinks to fetch.
   */
  orderBy?: Prisma.SourceLinkOrderByWithRelationInput | Prisma.SourceLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SourceLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SourceLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SourceLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SourceLinks
  **/
  _count?: true | SourceLinkCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SourceLinkMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SourceLinkMaxAggregateInputType
}

export type GetSourceLinkAggregateType<T extends SourceLinkAggregateArgs> = {
      [P in keyof T & keyof AggregateSourceLink]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSourceLink[P]>
    : Prisma.GetScalarType<T[P], AggregateSourceLink[P]>
}




export type SourceLinkGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SourceLinkWhereInput
  orderBy?: Prisma.SourceLinkOrderByWithAggregationInput | Prisma.SourceLinkOrderByWithAggregationInput[]
  by: Prisma.SourceLinkScalarFieldEnum[] | Prisma.SourceLinkScalarFieldEnum
  having?: Prisma.SourceLinkScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SourceLinkCountAggregateInputType | true
  _min?: SourceLinkMinAggregateInputType
  _max?: SourceLinkMaxAggregateInputType
}

export type SourceLinkGroupByOutputType = {
  dataSourceId: string
  chartId: string
  config: runtime.JsonValue | null
  createdAt: Date
  updatedAt: Date
  _count: SourceLinkCountAggregateOutputType | null
  _min: SourceLinkMinAggregateOutputType | null
  _max: SourceLinkMaxAggregateOutputType | null
}

type GetSourceLinkGroupByPayload<T extends SourceLinkGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SourceLinkGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SourceLinkGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SourceLinkGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SourceLinkGroupByOutputType[P]>
      }
    >
  >



export type SourceLinkWhereInput = {
  AND?: Prisma.SourceLinkWhereInput | Prisma.SourceLinkWhereInput[]
  OR?: Prisma.SourceLinkWhereInput[]
  NOT?: Prisma.SourceLinkWhereInput | Prisma.SourceLinkWhereInput[]
  dataSourceId?: Prisma.StringFilter<"SourceLink"> | string
  chartId?: Prisma.StringFilter<"SourceLink"> | string
  config?: Prisma.JsonNullableFilter<"SourceLink">
  createdAt?: Prisma.DateTimeFilter<"SourceLink"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SourceLink"> | Date | string
  dataSource?: Prisma.XOR<Prisma.DataSourceScalarRelationFilter, Prisma.DataSourceWhereInput>
  chart?: Prisma.XOR<Prisma.ChartScalarRelationFilter, Prisma.ChartWhereInput>
}

export type SourceLinkOrderByWithRelationInput = {
  dataSourceId?: Prisma.SortOrder
  chartId?: Prisma.SortOrder
  config?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  dataSource?: Prisma.DataSourceOrderByWithRelationInput
  chart?: Prisma.ChartOrderByWithRelationInput
}

export type SourceLinkWhereUniqueInput = Prisma.AtLeast<{
  dataSourceId_chartId?: Prisma.SourceLinkDataSourceIdChartIdCompoundUniqueInput
  AND?: Prisma.SourceLinkWhereInput | Prisma.SourceLinkWhereInput[]
  OR?: Prisma.SourceLinkWhereInput[]
  NOT?: Prisma.SourceLinkWhereInput | Prisma.SourceLinkWhereInput[]
  dataSourceId?: Prisma.StringFilter<"SourceLink"> | string
  chartId?: Prisma.StringFilter<"SourceLink"> | string
  config?: Prisma.JsonNullableFilter<"SourceLink">
  createdAt?: Prisma.DateTimeFilter<"SourceLink"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SourceLink"> | Date | string
  dataSource?: Prisma.XOR<Prisma.DataSourceScalarRelationFilter, Prisma.DataSourceWhereInput>
  chart?: Prisma.XOR<Prisma.ChartScalarRelationFilter, Prisma.ChartWhereInput>
}, "dataSourceId_chartId">

export type SourceLinkOrderByWithAggregationInput = {
  dataSourceId?: Prisma.SortOrder
  chartId?: Prisma.SortOrder
  config?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SourceLinkCountOrderByAggregateInput
  _max?: Prisma.SourceLinkMaxOrderByAggregateInput
  _min?: Prisma.SourceLinkMinOrderByAggregateInput
}

export type SourceLinkScalarWhereWithAggregatesInput = {
  AND?: Prisma.SourceLinkScalarWhereWithAggregatesInput | Prisma.SourceLinkScalarWhereWithAggregatesInput[]
  OR?: Prisma.SourceLinkScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SourceLinkScalarWhereWithAggregatesInput | Prisma.SourceLinkScalarWhereWithAggregatesInput[]
  dataSourceId?: Prisma.StringWithAggregatesFilter<"SourceLink"> | string
  chartId?: Prisma.StringWithAggregatesFilter<"SourceLink"> | string
  config?: Prisma.JsonNullableWithAggregatesFilter<"SourceLink">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SourceLink"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"SourceLink"> | Date | string
}

export type SourceLinkCreateInput = {
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  dataSource: Prisma.DataSourceCreateNestedOneWithoutSourceLinkInput
  chart: Prisma.ChartCreateNestedOneWithoutSourceLinkInput
}

export type SourceLinkUncheckedCreateInput = {
  dataSourceId: string
  chartId: string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SourceLinkUpdateInput = {
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dataSource?: Prisma.DataSourceUpdateOneRequiredWithoutSourceLinkNestedInput
  chart?: Prisma.ChartUpdateOneRequiredWithoutSourceLinkNestedInput
}

export type SourceLinkUncheckedUpdateInput = {
  dataSourceId?: Prisma.StringFieldUpdateOperationsInput | string
  chartId?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SourceLinkCreateManyInput = {
  dataSourceId: string
  chartId: string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SourceLinkUpdateManyMutationInput = {
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SourceLinkUncheckedUpdateManyInput = {
  dataSourceId?: Prisma.StringFieldUpdateOperationsInput | string
  chartId?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SourceLinkListRelationFilter = {
  every?: Prisma.SourceLinkWhereInput
  some?: Prisma.SourceLinkWhereInput
  none?: Prisma.SourceLinkWhereInput
}

export type SourceLinkOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SourceLinkDataSourceIdChartIdCompoundUniqueInput = {
  dataSourceId: string
  chartId: string
}

export type SourceLinkCountOrderByAggregateInput = {
  dataSourceId?: Prisma.SortOrder
  chartId?: Prisma.SortOrder
  config?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SourceLinkMaxOrderByAggregateInput = {
  dataSourceId?: Prisma.SortOrder
  chartId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SourceLinkMinOrderByAggregateInput = {
  dataSourceId?: Prisma.SortOrder
  chartId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SourceLinkCreateNestedManyWithoutDataSourceInput = {
  create?: Prisma.XOR<Prisma.SourceLinkCreateWithoutDataSourceInput, Prisma.SourceLinkUncheckedCreateWithoutDataSourceInput> | Prisma.SourceLinkCreateWithoutDataSourceInput[] | Prisma.SourceLinkUncheckedCreateWithoutDataSourceInput[]
  connectOrCreate?: Prisma.SourceLinkCreateOrConnectWithoutDataSourceInput | Prisma.SourceLinkCreateOrConnectWithoutDataSourceInput[]
  createMany?: Prisma.SourceLinkCreateManyDataSourceInputEnvelope
  connect?: Prisma.SourceLinkWhereUniqueInput | Prisma.SourceLinkWhereUniqueInput[]
}

export type SourceLinkUncheckedCreateNestedManyWithoutDataSourceInput = {
  create?: Prisma.XOR<Prisma.SourceLinkCreateWithoutDataSourceInput, Prisma.SourceLinkUncheckedCreateWithoutDataSourceInput> | Prisma.SourceLinkCreateWithoutDataSourceInput[] | Prisma.SourceLinkUncheckedCreateWithoutDataSourceInput[]
  connectOrCreate?: Prisma.SourceLinkCreateOrConnectWithoutDataSourceInput | Prisma.SourceLinkCreateOrConnectWithoutDataSourceInput[]
  createMany?: Prisma.SourceLinkCreateManyDataSourceInputEnvelope
  connect?: Prisma.SourceLinkWhereUniqueInput | Prisma.SourceLinkWhereUniqueInput[]
}

export type SourceLinkUpdateManyWithoutDataSourceNestedInput = {
  create?: Prisma.XOR<Prisma.SourceLinkCreateWithoutDataSourceInput, Prisma.SourceLinkUncheckedCreateWithoutDataSourceInput> | Prisma.SourceLinkCreateWithoutDataSourceInput[] | Prisma.SourceLinkUncheckedCreateWithoutDataSourceInput[]
  connectOrCreate?: Prisma.SourceLinkCreateOrConnectWithoutDataSourceInput | Prisma.SourceLinkCreateOrConnectWithoutDataSourceInput[]
  upsert?: Prisma.SourceLinkUpsertWithWhereUniqueWithoutDataSourceInput | Prisma.SourceLinkUpsertWithWhereUniqueWithoutDataSourceInput[]
  createMany?: Prisma.SourceLinkCreateManyDataSourceInputEnvelope
  set?: Prisma.SourceLinkWhereUniqueInput | Prisma.SourceLinkWhereUniqueInput[]
  disconnect?: Prisma.SourceLinkWhereUniqueInput | Prisma.SourceLinkWhereUniqueInput[]
  delete?: Prisma.SourceLinkWhereUniqueInput | Prisma.SourceLinkWhereUniqueInput[]
  connect?: Prisma.SourceLinkWhereUniqueInput | Prisma.SourceLinkWhereUniqueInput[]
  update?: Prisma.SourceLinkUpdateWithWhereUniqueWithoutDataSourceInput | Prisma.SourceLinkUpdateWithWhereUniqueWithoutDataSourceInput[]
  updateMany?: Prisma.SourceLinkUpdateManyWithWhereWithoutDataSourceInput | Prisma.SourceLinkUpdateManyWithWhereWithoutDataSourceInput[]
  deleteMany?: Prisma.SourceLinkScalarWhereInput | Prisma.SourceLinkScalarWhereInput[]
}

export type SourceLinkUncheckedUpdateManyWithoutDataSourceNestedInput = {
  create?: Prisma.XOR<Prisma.SourceLinkCreateWithoutDataSourceInput, Prisma.SourceLinkUncheckedCreateWithoutDataSourceInput> | Prisma.SourceLinkCreateWithoutDataSourceInput[] | Prisma.SourceLinkUncheckedCreateWithoutDataSourceInput[]
  connectOrCreate?: Prisma.SourceLinkCreateOrConnectWithoutDataSourceInput | Prisma.SourceLinkCreateOrConnectWithoutDataSourceInput[]
  upsert?: Prisma.SourceLinkUpsertWithWhereUniqueWithoutDataSourceInput | Prisma.SourceLinkUpsertWithWhereUniqueWithoutDataSourceInput[]
  createMany?: Prisma.SourceLinkCreateManyDataSourceInputEnvelope
  set?: Prisma.SourceLinkWhereUniqueInput | Prisma.SourceLinkWhereUniqueInput[]
  disconnect?: Prisma.SourceLinkWhereUniqueInput | Prisma.SourceLinkWhereUniqueInput[]
  delete?: Prisma.SourceLinkWhereUniqueInput | Prisma.SourceLinkWhereUniqueInput[]
  connect?: Prisma.SourceLinkWhereUniqueInput | Prisma.SourceLinkWhereUniqueInput[]
  update?: Prisma.SourceLinkUpdateWithWhereUniqueWithoutDataSourceInput | Prisma.SourceLinkUpdateWithWhereUniqueWithoutDataSourceInput[]
  updateMany?: Prisma.SourceLinkUpdateManyWithWhereWithoutDataSourceInput | Prisma.SourceLinkUpdateManyWithWhereWithoutDataSourceInput[]
  deleteMany?: Prisma.SourceLinkScalarWhereInput | Prisma.SourceLinkScalarWhereInput[]
}

export type SourceLinkCreateNestedManyWithoutChartInput = {
  create?: Prisma.XOR<Prisma.SourceLinkCreateWithoutChartInput, Prisma.SourceLinkUncheckedCreateWithoutChartInput> | Prisma.SourceLinkCreateWithoutChartInput[] | Prisma.SourceLinkUncheckedCreateWithoutChartInput[]
  connectOrCreate?: Prisma.SourceLinkCreateOrConnectWithoutChartInput | Prisma.SourceLinkCreateOrConnectWithoutChartInput[]
  createMany?: Prisma.SourceLinkCreateManyChartInputEnvelope
  connect?: Prisma.SourceLinkWhereUniqueInput | Prisma.SourceLinkWhereUniqueInput[]
}

export type SourceLinkUncheckedCreateNestedManyWithoutChartInput = {
  create?: Prisma.XOR<Prisma.SourceLinkCreateWithoutChartInput, Prisma.SourceLinkUncheckedCreateWithoutChartInput> | Prisma.SourceLinkCreateWithoutChartInput[] | Prisma.SourceLinkUncheckedCreateWithoutChartInput[]
  connectOrCreate?: Prisma.SourceLinkCreateOrConnectWithoutChartInput | Prisma.SourceLinkCreateOrConnectWithoutChartInput[]
  createMany?: Prisma.SourceLinkCreateManyChartInputEnvelope
  connect?: Prisma.SourceLinkWhereUniqueInput | Prisma.SourceLinkWhereUniqueInput[]
}

export type SourceLinkUpdateManyWithoutChartNestedInput = {
  create?: Prisma.XOR<Prisma.SourceLinkCreateWithoutChartInput, Prisma.SourceLinkUncheckedCreateWithoutChartInput> | Prisma.SourceLinkCreateWithoutChartInput[] | Prisma.SourceLinkUncheckedCreateWithoutChartInput[]
  connectOrCreate?: Prisma.SourceLinkCreateOrConnectWithoutChartInput | Prisma.SourceLinkCreateOrConnectWithoutChartInput[]
  upsert?: Prisma.SourceLinkUpsertWithWhereUniqueWithoutChartInput | Prisma.SourceLinkUpsertWithWhereUniqueWithoutChartInput[]
  createMany?: Prisma.SourceLinkCreateManyChartInputEnvelope
  set?: Prisma.SourceLinkWhereUniqueInput | Prisma.SourceLinkWhereUniqueInput[]
  disconnect?: Prisma.SourceLinkWhereUniqueInput | Prisma.SourceLinkWhereUniqueInput[]
  delete?: Prisma.SourceLinkWhereUniqueInput | Prisma.SourceLinkWhereUniqueInput[]
  connect?: Prisma.SourceLinkWhereUniqueInput | Prisma.SourceLinkWhereUniqueInput[]
  update?: Prisma.SourceLinkUpdateWithWhereUniqueWithoutChartInput | Prisma.SourceLinkUpdateWithWhereUniqueWithoutChartInput[]
  updateMany?: Prisma.SourceLinkUpdateManyWithWhereWithoutChartInput | Prisma.SourceLinkUpdateManyWithWhereWithoutChartInput[]
  deleteMany?: Prisma.SourceLinkScalarWhereInput | Prisma.SourceLinkScalarWhereInput[]
}

export type SourceLinkUncheckedUpdateManyWithoutChartNestedInput = {
  create?: Prisma.XOR<Prisma.SourceLinkCreateWithoutChartInput, Prisma.SourceLinkUncheckedCreateWithoutChartInput> | Prisma.SourceLinkCreateWithoutChartInput[] | Prisma.SourceLinkUncheckedCreateWithoutChartInput[]
  connectOrCreate?: Prisma.SourceLinkCreateOrConnectWithoutChartInput | Prisma.SourceLinkCreateOrConnectWithoutChartInput[]
  upsert?: Prisma.SourceLinkUpsertWithWhereUniqueWithoutChartInput | Prisma.SourceLinkUpsertWithWhereUniqueWithoutChartInput[]
  createMany?: Prisma.SourceLinkCreateManyChartInputEnvelope
  set?: Prisma.SourceLinkWhereUniqueInput | Prisma.SourceLinkWhereUniqueInput[]
  disconnect?: Prisma.SourceLinkWhereUniqueInput | Prisma.SourceLinkWhereUniqueInput[]
  delete?: Prisma.SourceLinkWhereUniqueInput | Prisma.SourceLinkWhereUniqueInput[]
  connect?: Prisma.SourceLinkWhereUniqueInput | Prisma.SourceLinkWhereUniqueInput[]
  update?: Prisma.SourceLinkUpdateWithWhereUniqueWithoutChartInput | Prisma.SourceLinkUpdateWithWhereUniqueWithoutChartInput[]
  updateMany?: Prisma.SourceLinkUpdateManyWithWhereWithoutChartInput | Prisma.SourceLinkUpdateManyWithWhereWithoutChartInput[]
  deleteMany?: Prisma.SourceLinkScalarWhereInput | Prisma.SourceLinkScalarWhereInput[]
}

export type SourceLinkCreateWithoutDataSourceInput = {
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  chart: Prisma.ChartCreateNestedOneWithoutSourceLinkInput
}

export type SourceLinkUncheckedCreateWithoutDataSourceInput = {
  chartId: string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SourceLinkCreateOrConnectWithoutDataSourceInput = {
  where: Prisma.SourceLinkWhereUniqueInput
  create: Prisma.XOR<Prisma.SourceLinkCreateWithoutDataSourceInput, Prisma.SourceLinkUncheckedCreateWithoutDataSourceInput>
}

export type SourceLinkCreateManyDataSourceInputEnvelope = {
  data: Prisma.SourceLinkCreateManyDataSourceInput | Prisma.SourceLinkCreateManyDataSourceInput[]
  skipDuplicates?: boolean
}

export type SourceLinkUpsertWithWhereUniqueWithoutDataSourceInput = {
  where: Prisma.SourceLinkWhereUniqueInput
  update: Prisma.XOR<Prisma.SourceLinkUpdateWithoutDataSourceInput, Prisma.SourceLinkUncheckedUpdateWithoutDataSourceInput>
  create: Prisma.XOR<Prisma.SourceLinkCreateWithoutDataSourceInput, Prisma.SourceLinkUncheckedCreateWithoutDataSourceInput>
}

export type SourceLinkUpdateWithWhereUniqueWithoutDataSourceInput = {
  where: Prisma.SourceLinkWhereUniqueInput
  data: Prisma.XOR<Prisma.SourceLinkUpdateWithoutDataSourceInput, Prisma.SourceLinkUncheckedUpdateWithoutDataSourceInput>
}

export type SourceLinkUpdateManyWithWhereWithoutDataSourceInput = {
  where: Prisma.SourceLinkScalarWhereInput
  data: Prisma.XOR<Prisma.SourceLinkUpdateManyMutationInput, Prisma.SourceLinkUncheckedUpdateManyWithoutDataSourceInput>
}

export type SourceLinkScalarWhereInput = {
  AND?: Prisma.SourceLinkScalarWhereInput | Prisma.SourceLinkScalarWhereInput[]
  OR?: Prisma.SourceLinkScalarWhereInput[]
  NOT?: Prisma.SourceLinkScalarWhereInput | Prisma.SourceLinkScalarWhereInput[]
  dataSourceId?: Prisma.StringFilter<"SourceLink"> | string
  chartId?: Prisma.StringFilter<"SourceLink"> | string
  config?: Prisma.JsonNullableFilter<"SourceLink">
  createdAt?: Prisma.DateTimeFilter<"SourceLink"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SourceLink"> | Date | string
}

export type SourceLinkCreateWithoutChartInput = {
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  dataSource: Prisma.DataSourceCreateNestedOneWithoutSourceLinkInput
}

export type SourceLinkUncheckedCreateWithoutChartInput = {
  dataSourceId: string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SourceLinkCreateOrConnectWithoutChartInput = {
  where: Prisma.SourceLinkWhereUniqueInput
  create: Prisma.XOR<Prisma.SourceLinkCreateWithoutChartInput, Prisma.SourceLinkUncheckedCreateWithoutChartInput>
}

export type SourceLinkCreateManyChartInputEnvelope = {
  data: Prisma.SourceLinkCreateManyChartInput | Prisma.SourceLinkCreateManyChartInput[]
  skipDuplicates?: boolean
}

export type SourceLinkUpsertWithWhereUniqueWithoutChartInput = {
  where: Prisma.SourceLinkWhereUniqueInput
  update: Prisma.XOR<Prisma.SourceLinkUpdateWithoutChartInput, Prisma.SourceLinkUncheckedUpdateWithoutChartInput>
  create: Prisma.XOR<Prisma.SourceLinkCreateWithoutChartInput, Prisma.SourceLinkUncheckedCreateWithoutChartInput>
}

export type SourceLinkUpdateWithWhereUniqueWithoutChartInput = {
  where: Prisma.SourceLinkWhereUniqueInput
  data: Prisma.XOR<Prisma.SourceLinkUpdateWithoutChartInput, Prisma.SourceLinkUncheckedUpdateWithoutChartInput>
}

export type SourceLinkUpdateManyWithWhereWithoutChartInput = {
  where: Prisma.SourceLinkScalarWhereInput
  data: Prisma.XOR<Prisma.SourceLinkUpdateManyMutationInput, Prisma.SourceLinkUncheckedUpdateManyWithoutChartInput>
}

export type SourceLinkCreateManyDataSourceInput = {
  chartId: string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SourceLinkUpdateWithoutDataSourceInput = {
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  chart?: Prisma.ChartUpdateOneRequiredWithoutSourceLinkNestedInput
}

export type SourceLinkUncheckedUpdateWithoutDataSourceInput = {
  chartId?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SourceLinkUncheckedUpdateManyWithoutDataSourceInput = {
  chartId?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SourceLinkCreateManyChartInput = {
  dataSourceId: string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SourceLinkUpdateWithoutChartInput = {
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  dataSource?: Prisma.DataSourceUpdateOneRequiredWithoutSourceLinkNestedInput
}

export type SourceLinkUncheckedUpdateWithoutChartInput = {
  dataSourceId?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SourceLinkUncheckedUpdateManyWithoutChartInput = {
  dataSourceId?: Prisma.StringFieldUpdateOperationsInput | string
  config?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type SourceLinkSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  dataSourceId?: boolean
  chartId?: boolean
  config?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  dataSource?: boolean | Prisma.DataSourceDefaultArgs<ExtArgs>
  chart?: boolean | Prisma.ChartDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sourceLink"]>

export type SourceLinkSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  dataSourceId?: boolean
  chartId?: boolean
  config?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  dataSource?: boolean | Prisma.DataSourceDefaultArgs<ExtArgs>
  chart?: boolean | Prisma.ChartDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sourceLink"]>

export type SourceLinkSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  dataSourceId?: boolean
  chartId?: boolean
  config?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  dataSource?: boolean | Prisma.DataSourceDefaultArgs<ExtArgs>
  chart?: boolean | Prisma.ChartDefaultArgs<ExtArgs>
}, ExtArgs["result"]["sourceLink"]>

export type SourceLinkSelectScalar = {
  dataSourceId?: boolean
  chartId?: boolean
  config?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type SourceLinkOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"dataSourceId" | "chartId" | "config" | "createdAt" | "updatedAt", ExtArgs["result"]["sourceLink"]>
export type SourceLinkInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dataSource?: boolean | Prisma.DataSourceDefaultArgs<ExtArgs>
  chart?: boolean | Prisma.ChartDefaultArgs<ExtArgs>
}
export type SourceLinkIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dataSource?: boolean | Prisma.DataSourceDefaultArgs<ExtArgs>
  chart?: boolean | Prisma.ChartDefaultArgs<ExtArgs>
}
export type SourceLinkIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  dataSource?: boolean | Prisma.DataSourceDefaultArgs<ExtArgs>
  chart?: boolean | Prisma.ChartDefaultArgs<ExtArgs>
}

export type $SourceLinkPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SourceLink"
  objects: {
    dataSource: Prisma.$DataSourcePayload<ExtArgs>
    chart: Prisma.$ChartPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    dataSourceId: string
    chartId: string
    config: runtime.JsonValue | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["sourceLink"]>
  composites: {}
}

export type SourceLinkGetPayload<S extends boolean | null | undefined | SourceLinkDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SourceLinkPayload, S>

export type SourceLinkCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SourceLinkFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SourceLinkCountAggregateInputType | true
  }

export interface SourceLinkDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SourceLink'], meta: { name: 'SourceLink' } }
  /**
   * Find zero or one SourceLink that matches the filter.
   * @param {SourceLinkFindUniqueArgs} args - Arguments to find a SourceLink
   * @example
   * // Get one SourceLink
   * const sourceLink = await prisma.sourceLink.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SourceLinkFindUniqueArgs>(args: Prisma.SelectSubset<T, SourceLinkFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SourceLinkClient<runtime.Types.Result.GetResult<Prisma.$SourceLinkPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SourceLink that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SourceLinkFindUniqueOrThrowArgs} args - Arguments to find a SourceLink
   * @example
   * // Get one SourceLink
   * const sourceLink = await prisma.sourceLink.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SourceLinkFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SourceLinkFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SourceLinkClient<runtime.Types.Result.GetResult<Prisma.$SourceLinkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SourceLink that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceLinkFindFirstArgs} args - Arguments to find a SourceLink
   * @example
   * // Get one SourceLink
   * const sourceLink = await prisma.sourceLink.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SourceLinkFindFirstArgs>(args?: Prisma.SelectSubset<T, SourceLinkFindFirstArgs<ExtArgs>>): Prisma.Prisma__SourceLinkClient<runtime.Types.Result.GetResult<Prisma.$SourceLinkPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SourceLink that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceLinkFindFirstOrThrowArgs} args - Arguments to find a SourceLink
   * @example
   * // Get one SourceLink
   * const sourceLink = await prisma.sourceLink.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SourceLinkFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SourceLinkFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SourceLinkClient<runtime.Types.Result.GetResult<Prisma.$SourceLinkPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SourceLinks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceLinkFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SourceLinks
   * const sourceLinks = await prisma.sourceLink.findMany()
   * 
   * // Get first 10 SourceLinks
   * const sourceLinks = await prisma.sourceLink.findMany({ take: 10 })
   * 
   * // Only select the `dataSourceId`
   * const sourceLinkWithDataSourceIdOnly = await prisma.sourceLink.findMany({ select: { dataSourceId: true } })
   * 
   */
  findMany<T extends SourceLinkFindManyArgs>(args?: Prisma.SelectSubset<T, SourceLinkFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SourceLinkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SourceLink.
   * @param {SourceLinkCreateArgs} args - Arguments to create a SourceLink.
   * @example
   * // Create one SourceLink
   * const SourceLink = await prisma.sourceLink.create({
   *   data: {
   *     // ... data to create a SourceLink
   *   }
   * })
   * 
   */
  create<T extends SourceLinkCreateArgs>(args: Prisma.SelectSubset<T, SourceLinkCreateArgs<ExtArgs>>): Prisma.Prisma__SourceLinkClient<runtime.Types.Result.GetResult<Prisma.$SourceLinkPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SourceLinks.
   * @param {SourceLinkCreateManyArgs} args - Arguments to create many SourceLinks.
   * @example
   * // Create many SourceLinks
   * const sourceLink = await prisma.sourceLink.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SourceLinkCreateManyArgs>(args?: Prisma.SelectSubset<T, SourceLinkCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SourceLinks and returns the data saved in the database.
   * @param {SourceLinkCreateManyAndReturnArgs} args - Arguments to create many SourceLinks.
   * @example
   * // Create many SourceLinks
   * const sourceLink = await prisma.sourceLink.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SourceLinks and only return the `dataSourceId`
   * const sourceLinkWithDataSourceIdOnly = await prisma.sourceLink.createManyAndReturn({
   *   select: { dataSourceId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SourceLinkCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SourceLinkCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SourceLinkPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SourceLink.
   * @param {SourceLinkDeleteArgs} args - Arguments to delete one SourceLink.
   * @example
   * // Delete one SourceLink
   * const SourceLink = await prisma.sourceLink.delete({
   *   where: {
   *     // ... filter to delete one SourceLink
   *   }
   * })
   * 
   */
  delete<T extends SourceLinkDeleteArgs>(args: Prisma.SelectSubset<T, SourceLinkDeleteArgs<ExtArgs>>): Prisma.Prisma__SourceLinkClient<runtime.Types.Result.GetResult<Prisma.$SourceLinkPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SourceLink.
   * @param {SourceLinkUpdateArgs} args - Arguments to update one SourceLink.
   * @example
   * // Update one SourceLink
   * const sourceLink = await prisma.sourceLink.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SourceLinkUpdateArgs>(args: Prisma.SelectSubset<T, SourceLinkUpdateArgs<ExtArgs>>): Prisma.Prisma__SourceLinkClient<runtime.Types.Result.GetResult<Prisma.$SourceLinkPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SourceLinks.
   * @param {SourceLinkDeleteManyArgs} args - Arguments to filter SourceLinks to delete.
   * @example
   * // Delete a few SourceLinks
   * const { count } = await prisma.sourceLink.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SourceLinkDeleteManyArgs>(args?: Prisma.SelectSubset<T, SourceLinkDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SourceLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceLinkUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SourceLinks
   * const sourceLink = await prisma.sourceLink.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SourceLinkUpdateManyArgs>(args: Prisma.SelectSubset<T, SourceLinkUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SourceLinks and returns the data updated in the database.
   * @param {SourceLinkUpdateManyAndReturnArgs} args - Arguments to update many SourceLinks.
   * @example
   * // Update many SourceLinks
   * const sourceLink = await prisma.sourceLink.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SourceLinks and only return the `dataSourceId`
   * const sourceLinkWithDataSourceIdOnly = await prisma.sourceLink.updateManyAndReturn({
   *   select: { dataSourceId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SourceLinkUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SourceLinkUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SourceLinkPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SourceLink.
   * @param {SourceLinkUpsertArgs} args - Arguments to update or create a SourceLink.
   * @example
   * // Update or create a SourceLink
   * const sourceLink = await prisma.sourceLink.upsert({
   *   create: {
   *     // ... data to create a SourceLink
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SourceLink we want to update
   *   }
   * })
   */
  upsert<T extends SourceLinkUpsertArgs>(args: Prisma.SelectSubset<T, SourceLinkUpsertArgs<ExtArgs>>): Prisma.Prisma__SourceLinkClient<runtime.Types.Result.GetResult<Prisma.$SourceLinkPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SourceLinks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceLinkCountArgs} args - Arguments to filter SourceLinks to count.
   * @example
   * // Count the number of SourceLinks
   * const count = await prisma.sourceLink.count({
   *   where: {
   *     // ... the filter for the SourceLinks we want to count
   *   }
   * })
  **/
  count<T extends SourceLinkCountArgs>(
    args?: Prisma.Subset<T, SourceLinkCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SourceLinkCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SourceLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceLinkAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SourceLinkAggregateArgs>(args: Prisma.Subset<T, SourceLinkAggregateArgs>): Prisma.PrismaPromise<GetSourceLinkAggregateType<T>>

  /**
   * Group by SourceLink.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SourceLinkGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SourceLinkGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SourceLinkGroupByArgs['orderBy'] }
      : { orderBy?: SourceLinkGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SourceLinkGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSourceLinkGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SourceLink model
 */
readonly fields: SourceLinkFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SourceLink.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SourceLinkClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  dataSource<T extends Prisma.DataSourceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DataSourceDefaultArgs<ExtArgs>>): Prisma.Prisma__DataSourceClient<runtime.Types.Result.GetResult<Prisma.$DataSourcePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  chart<T extends Prisma.ChartDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ChartDefaultArgs<ExtArgs>>): Prisma.Prisma__ChartClient<runtime.Types.Result.GetResult<Prisma.$ChartPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SourceLink model
 */
export interface SourceLinkFieldRefs {
  readonly dataSourceId: Prisma.FieldRef<"SourceLink", 'String'>
  readonly chartId: Prisma.FieldRef<"SourceLink", 'String'>
  readonly config: Prisma.FieldRef<"SourceLink", 'Json'>
  readonly createdAt: Prisma.FieldRef<"SourceLink", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"SourceLink", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SourceLink findUnique
 */
export type SourceLinkFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceLink
   */
  select?: Prisma.SourceLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceLink
   */
  omit?: Prisma.SourceLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceLinkInclude<ExtArgs> | null
  /**
   * Filter, which SourceLink to fetch.
   */
  where: Prisma.SourceLinkWhereUniqueInput
}

/**
 * SourceLink findUniqueOrThrow
 */
export type SourceLinkFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceLink
   */
  select?: Prisma.SourceLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceLink
   */
  omit?: Prisma.SourceLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceLinkInclude<ExtArgs> | null
  /**
   * Filter, which SourceLink to fetch.
   */
  where: Prisma.SourceLinkWhereUniqueInput
}

/**
 * SourceLink findFirst
 */
export type SourceLinkFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceLink
   */
  select?: Prisma.SourceLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceLink
   */
  omit?: Prisma.SourceLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceLinkInclude<ExtArgs> | null
  /**
   * Filter, which SourceLink to fetch.
   */
  where?: Prisma.SourceLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SourceLinks to fetch.
   */
  orderBy?: Prisma.SourceLinkOrderByWithRelationInput | Prisma.SourceLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SourceLinks.
   */
  cursor?: Prisma.SourceLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SourceLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SourceLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SourceLinks.
   */
  distinct?: Prisma.SourceLinkScalarFieldEnum | Prisma.SourceLinkScalarFieldEnum[]
}

/**
 * SourceLink findFirstOrThrow
 */
export type SourceLinkFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceLink
   */
  select?: Prisma.SourceLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceLink
   */
  omit?: Prisma.SourceLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceLinkInclude<ExtArgs> | null
  /**
   * Filter, which SourceLink to fetch.
   */
  where?: Prisma.SourceLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SourceLinks to fetch.
   */
  orderBy?: Prisma.SourceLinkOrderByWithRelationInput | Prisma.SourceLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SourceLinks.
   */
  cursor?: Prisma.SourceLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SourceLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SourceLinks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SourceLinks.
   */
  distinct?: Prisma.SourceLinkScalarFieldEnum | Prisma.SourceLinkScalarFieldEnum[]
}

/**
 * SourceLink findMany
 */
export type SourceLinkFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceLink
   */
  select?: Prisma.SourceLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceLink
   */
  omit?: Prisma.SourceLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceLinkInclude<ExtArgs> | null
  /**
   * Filter, which SourceLinks to fetch.
   */
  where?: Prisma.SourceLinkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SourceLinks to fetch.
   */
  orderBy?: Prisma.SourceLinkOrderByWithRelationInput | Prisma.SourceLinkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SourceLinks.
   */
  cursor?: Prisma.SourceLinkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SourceLinks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SourceLinks.
   */
  skip?: number
  distinct?: Prisma.SourceLinkScalarFieldEnum | Prisma.SourceLinkScalarFieldEnum[]
}

/**
 * SourceLink create
 */
export type SourceLinkCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceLink
   */
  select?: Prisma.SourceLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceLink
   */
  omit?: Prisma.SourceLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceLinkInclude<ExtArgs> | null
  /**
   * The data needed to create a SourceLink.
   */
  data: Prisma.XOR<Prisma.SourceLinkCreateInput, Prisma.SourceLinkUncheckedCreateInput>
}

/**
 * SourceLink createMany
 */
export type SourceLinkCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SourceLinks.
   */
  data: Prisma.SourceLinkCreateManyInput | Prisma.SourceLinkCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SourceLink createManyAndReturn
 */
export type SourceLinkCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceLink
   */
  select?: Prisma.SourceLinkSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SourceLink
   */
  omit?: Prisma.SourceLinkOmit<ExtArgs> | null
  /**
   * The data used to create many SourceLinks.
   */
  data: Prisma.SourceLinkCreateManyInput | Prisma.SourceLinkCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceLinkIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SourceLink update
 */
export type SourceLinkUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceLink
   */
  select?: Prisma.SourceLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceLink
   */
  omit?: Prisma.SourceLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceLinkInclude<ExtArgs> | null
  /**
   * The data needed to update a SourceLink.
   */
  data: Prisma.XOR<Prisma.SourceLinkUpdateInput, Prisma.SourceLinkUncheckedUpdateInput>
  /**
   * Choose, which SourceLink to update.
   */
  where: Prisma.SourceLinkWhereUniqueInput
}

/**
 * SourceLink updateMany
 */
export type SourceLinkUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SourceLinks.
   */
  data: Prisma.XOR<Prisma.SourceLinkUpdateManyMutationInput, Prisma.SourceLinkUncheckedUpdateManyInput>
  /**
   * Filter which SourceLinks to update
   */
  where?: Prisma.SourceLinkWhereInput
  /**
   * Limit how many SourceLinks to update.
   */
  limit?: number
}

/**
 * SourceLink updateManyAndReturn
 */
export type SourceLinkUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceLink
   */
  select?: Prisma.SourceLinkSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SourceLink
   */
  omit?: Prisma.SourceLinkOmit<ExtArgs> | null
  /**
   * The data used to update SourceLinks.
   */
  data: Prisma.XOR<Prisma.SourceLinkUpdateManyMutationInput, Prisma.SourceLinkUncheckedUpdateManyInput>
  /**
   * Filter which SourceLinks to update
   */
  where?: Prisma.SourceLinkWhereInput
  /**
   * Limit how many SourceLinks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceLinkIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SourceLink upsert
 */
export type SourceLinkUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceLink
   */
  select?: Prisma.SourceLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceLink
   */
  omit?: Prisma.SourceLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceLinkInclude<ExtArgs> | null
  /**
   * The filter to search for the SourceLink to update in case it exists.
   */
  where: Prisma.SourceLinkWhereUniqueInput
  /**
   * In case the SourceLink found by the `where` argument doesn't exist, create a new SourceLink with this data.
   */
  create: Prisma.XOR<Prisma.SourceLinkCreateInput, Prisma.SourceLinkUncheckedCreateInput>
  /**
   * In case the SourceLink was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SourceLinkUpdateInput, Prisma.SourceLinkUncheckedUpdateInput>
}

/**
 * SourceLink delete
 */
export type SourceLinkDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceLink
   */
  select?: Prisma.SourceLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceLink
   */
  omit?: Prisma.SourceLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceLinkInclude<ExtArgs> | null
  /**
   * Filter which SourceLink to delete.
   */
  where: Prisma.SourceLinkWhereUniqueInput
}

/**
 * SourceLink deleteMany
 */
export type SourceLinkDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SourceLinks to delete
   */
  where?: Prisma.SourceLinkWhereInput
  /**
   * Limit how many SourceLinks to delete.
   */
  limit?: number
}

/**
 * SourceLink without action
 */
export type SourceLinkDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SourceLink
   */
  select?: Prisma.SourceLinkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SourceLink
   */
  omit?: Prisma.SourceLinkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SourceLinkInclude<ExtArgs> | null
}
