/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */
import axios from "axios";
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  DeleteApiChartsById200,
  GetApiApikeys200Item,
  GetApiApikeysByIdLogs200Item,
  GetApiApikeysByIdLogsParams,
  GetApiAuthUser201,
  GetApiCharts200Item,
  GetApiChartsById200,
  GetApiChartsKpiGroupById200,
  GetApiChartsShowById200,
  GetApiDashboards200Item,
  GetApiDashboardsById200,
  GetApiDashboardsShowById200,
  GetApiDatasources200Item,
  GetApiDatasourcesById200,
  GetApiDatasourcesByIdLinks200Item,
  GetApiOrgs200Item,
  GetApiOrgsByOrgId200,
  GetApiOrgsByOrgIdMembers200Item,
  GetApiProjects200Item,
  GetApiProjectsByProjectId200,
  GetApiProjectsByProjectIdMembers200Item,
  GetApiProjectsPersonal200Item,
  PatchApiApikeysByIdReinstate200,
  PatchApiApikeysByIdRevoke200,
  PostApiApikeys201,
  PostApiApikeysBody,
  PostApiAuthLogin200,
  PostApiAuthLoginBody,
  PostApiAuthRecoverBody,
  PostApiAuthRegister200,
  PostApiAuthRegisterBody,
  PostApiAuthResendBody,
  PostApiAuthResetPassword200,
  PostApiAuthResetPasswordBody,
  PostApiAuthVerify200,
  PostApiAuthVerifyBody,
  PostApiCharts201,
  PostApiChartsBody,
  PostApiChartsKpiGroup201,
  PostApiChartsKpiGroupBody,
  PostApiChartsPublishById200,
  PostApiDashboards201,
  PostApiDashboardsBody,
  PostApiDatasources201,
  PostApiDatasourcesBody,
  PostApiDatasourcesByIdLinks201,
  PostApiDatasourcesByIdLinksBody,
  PostApiHints200Item,
  PostApiOrgs201,
  PostApiOrgsBody,
  PostApiOrgsByOrgIdMembers201,
  PostApiOrgsByOrgIdMembersBody,
  PostApiProjects201,
  PostApiProjectsBody,
  PostApiProjectsByProjectIdMembers201,
  PostApiProjectsByProjectIdMembersBody,
  PostApiProjectsByProjectIdOrgsBody,
  PutApiAuthPwdBody,
  PutApiChartsById200,
  PutApiChartsByIdBody,
  PutApiChartsKpiGroupById200,
  PutApiChartsKpiGroupByIdBody,
  PutApiDashboardsById200,
  PutApiDashboardsByIdBody,
  PutApiDashboardsByIdSlots200,
  PutApiDashboardsByIdSlotsBody,
  PutApiDatasourcesById200,
  PutApiDatasourcesByIdBody,
  PutApiOrgsByOrgId200,
  PutApiOrgsByOrgIdBody,
  PutApiOrgsByOrgIdMembersByUserId200,
  PutApiOrgsByOrgIdMembersByUserIdBody,
  PutApiProjectsByProjectId200,
  PutApiProjectsByProjectIdBody,
  PutApiProjectsByProjectIdMembersByUserId200,
  PutApiProjectsByProjectIdMembersByUserIdBody,
} from "./model";

export const getGraphItaliaAPI = (axiosInstance: AxiosInstance = axios) => {
  /**
   * List all users. Admin only.
   */
  const getApiAdminUsers = (
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<void>> => {
    return axiosInstance.get(`/api/admin/users`, options);
  };

  /**
   * Delete a user by id. Admin only.
   */
  const deleteApiAdminUsersById = (
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(`/api/admin/users/${id}`, options);
  };

  /**
   * Force-activate (verify) a user account. Admin only.
   */
  const postApiAdminUsersByIdActivate = (
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/admin/users/${id}/activate`,
      undefined,
      options,
    );
  };

  /**
   * Resend the activation email to an unverified user. Admin only.
   */
  const postApiAdminUsersByIdResendActivation = (
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/admin/users/${id}/resend-activation`,
      undefined,
      options,
    );
  };

  /**
   * Send a password reset email to a user. Admin only.
   */
  const postApiAdminUsersByIdResetPassword = (
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<void>> => {
    return axiosInstance.post(
      `/api/admin/users/${id}/reset-password`,
      undefined,
      options,
    );
  };

  /**
   * If the user is authenticated, returns the user information along with current token.
   */
  const getApiAuthUser = (
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<GetApiAuthUser201>> => {
    return axiosInstance.get(`/api/auth/user`, options);
  };

  /**
   * Register a new user with email and password.
   */
  const postApiAuthRegister = (
    postApiAuthRegisterBody?: PostApiAuthRegisterBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PostApiAuthRegister200>> => {
    return axiosInstance.post(
      `/api/auth/register`,
      postApiAuthRegisterBody,
      options,
    );
  };

  /**
   * Authenticate with email and password. Sets an access_token cookie on success.
   */
  const postApiAuthLogin = (
    postApiAuthLoginBody?: PostApiAuthLoginBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PostApiAuthLogin200>> => {
    return axiosInstance.post(`/api/auth/login`, postApiAuthLoginBody, options);
  };

  /**
   * Request a password reset email. Always returns success to prevent email enumeration.
   */
  const postApiAuthRecover = (
    postApiAuthRecoverBody?: PostApiAuthRecoverBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<boolean>> => {
    return axiosInstance.post(
      `/api/auth/recover`,
      postApiAuthRecoverBody,
      options,
    );
  };

  /**
   * Re-send the activation email to an unverified user. Always returns success to prevent email enumeration.
   */
  const postApiAuthResend = (
    postApiAuthResendBody?: PostApiAuthResendBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<boolean>> => {
    return axiosInstance.post(
      `/api/auth/resend`,
      postApiAuthResendBody,
      options,
    );
  };

  /**
   * Clear the access_token cookie and log the user out.
   */
  const getApiAuthLogout = (
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<boolean>> => {
    return axiosInstance.get(`/api/auth/logout`, options);
  };

  /**
   * Verify a user account using the PIN sent to their email.
   */
  const postApiAuthVerify = (
    postApiAuthVerifyBody?: PostApiAuthVerifyBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PostApiAuthVerify200>> => {
    return axiosInstance.post(
      `/api/auth/verify`,
      postApiAuthVerifyBody,
      options,
    );
  };

  /**
   * Confirm email via link (redirects to app on success).
   */
  const getApiAuthConfirmByUidByCode = (
    uid: string,
    code: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(`/api/auth/confirm/${uid}/${code}`, options);
  };

  /**
   * Reset password using a recovery code sent by email.
   */
  const postApiAuthResetPassword = (
    postApiAuthResetPasswordBody?: PostApiAuthResetPasswordBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PostApiAuthResetPassword200>> => {
    return axiosInstance.post(
      `/api/auth/reset-password`,
      postApiAuthResetPasswordBody,
      options,
    );
  };

  /**
   * Change the current user's password. Requires an active session.
   */
  const putApiAuthPwd = (
    putApiAuthPwdBody?: PutApiAuthPwdBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<void>> => {
    return axiosInstance.put(`/api/auth/pwd`, putApiAuthPwdBody, options);
  };

  /**
   * List all API keys for the current user across all accessible projects.
   */
  const getApiApikeys = (
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<GetApiApikeys200Item[]>> => {
    return axiosInstance.get(`/api/apikeys`, options);
  };

  /**
   * Create a new API key. The raw key is returned once and never shown again.
   */
  const postApiApikeys = (
    postApiApikeysBody?: PostApiApikeysBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PostApiApikeys201>> => {
    return axiosInstance.post(`/api/apikeys`, postApiApikeysBody, options);
  };

  /**
   * Delete an API key by ID. Requires ADMIN or owner access on the key's project.
   */
  const deleteApiApikeysById = (
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(`/api/apikeys/${id}`, options);
  };

  /**
   * Revoke an API key, disabling it without deleting it.
   */
  const patchApiApikeysByIdRevoke = (
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PatchApiApikeysByIdRevoke200>> => {
    return axiosInstance.patch(`/api/apikeys/${id}/revoke`, undefined, options);
  };

  /**
   * Reinstate a previously revoked API key.
   */
  const patchApiApikeysByIdReinstate = (
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PatchApiApikeysByIdReinstate200>> => {
    return axiosInstance.patch(
      `/api/apikeys/${id}/reinstate`,
      undefined,
      options,
    );
  };

  /**
   * Retrieve usage logs for a specific API key. Requires access to the key's project.
   */
  const getApiApikeysByIdLogs = (
    id: string,
    params?: GetApiApikeysByIdLogsParams,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<GetApiApikeysByIdLogs200Item[]>> => {
    return axiosInstance.get(`/api/apikeys/${id}/logs`, {
      ...options,
      params: { ...params, ...options?.params },
    });
  };

  const getApiCharts = (
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<GetApiCharts200Item[]>> => {
    return axiosInstance.get(`/api/charts`, options);
  };

  const postApiCharts = (
    postApiChartsBody?: PostApiChartsBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PostApiCharts201>> => {
    return axiosInstance.post(`/api/charts`, postApiChartsBody, options);
  };

  const getApiChartsById = (
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<GetApiChartsById200>> => {
    return axiosInstance.get(`/api/charts/${id}`, options);
  };

  const deleteApiChartsById = (
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<DeleteApiChartsById200>> => {
    return axiosInstance.delete(`/api/charts/${id}`, options);
  };

  const putApiChartsById = (
    id: string,
    putApiChartsByIdBody?: PutApiChartsByIdBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PutApiChartsById200>> => {
    return axiosInstance.put(
      `/api/charts/${id}`,
      putApiChartsByIdBody,
      options,
    );
  };

  const getApiChartsShowById = (
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<GetApiChartsShowById200>> => {
    return axiosInstance.get(`/api/charts/show/${id}`, options);
  };

  const postApiChartsPublishById = (
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PostApiChartsPublishById200>> => {
    return axiosInstance.post(`/api/charts/publish/${id}`, undefined, options);
  };

  /**
   * Create a new KPI group chart. Requires an authenticated user session (not API key).
   */
  const postApiChartsKpiGroup = (
    postApiChartsKpiGroupBody?: PostApiChartsKpiGroupBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PostApiChartsKpiGroup201>> => {
    return axiosInstance.post(
      `/api/charts/kpi-group`,
      postApiChartsKpiGroupBody,
      options,
    );
  };

  /**
   * Update a KPI group's config and data source items. Requires READWRITE access.
   */
  const putApiChartsKpiGroupById = (
    id: string,
    putApiChartsKpiGroupByIdBody?: PutApiChartsKpiGroupByIdBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PutApiChartsKpiGroupById200>> => {
    return axiosInstance.put(
      `/api/charts/kpi-group/${id}`,
      putApiChartsKpiGroupByIdBody,
      options,
    );
  };

  /**
   * Get a KPI group by ID including its config and data source items.
   */
  const getApiChartsKpiGroupById = (
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<GetApiChartsKpiGroupById200>> => {
    return axiosInstance.get(`/api/charts/kpi-group/${id}`, options);
  };

  /**
   * List all dashboards for the caller's project (resolved from API key or user session).
   */
  const getApiDashboards = (
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<GetApiDashboards200Item[]>> => {
    return axiosInstance.get(`/api/dashboards`, options);
  };

  /**
   * Create a new dashboard in the caller's project. Requires READWRITE API key or user session.
   */
  const postApiDashboards = (
    postApiDashboardsBody?: PostApiDashboardsBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PostApiDashboards201>> => {
    return axiosInstance.post(
      `/api/dashboards`,
      postApiDashboardsBody,
      options,
    );
  };

  /**
   * Get a single dashboard by ID including its chart slots.
   */
  const getApiDashboardsById = (
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<GetApiDashboardsById200>> => {
    return axiosInstance.get(`/api/dashboards/${id}`, options);
  };

  /**
   * Delete a dashboard by ID. Requires READWRITE access.
   */
  const deleteApiDashboardsById = (
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(`/api/dashboards/${id}`, options);
  };

  /**
   * Update dashboard metadata (name, description, publish state). Requires READWRITE access.
   */
  const putApiDashboardsById = (
    id: string,
    putApiDashboardsByIdBody?: PutApiDashboardsByIdBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PutApiDashboardsById200>> => {
    return axiosInstance.put(
      `/api/dashboards/${id}`,
      putApiDashboardsByIdBody,
      options,
    );
  };

  /**
   * Public endpoint — returns a published dashboard. No auth required.
   */
  const getApiDashboardsShowById = (
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<GetApiDashboardsShowById200>> => {
    return axiosInstance.get(`/api/dashboards/show/${id}`, options);
  };

  /**
   * Replace all chart slots for a dashboard. Requires READWRITE access.
   */
  const putApiDashboardsByIdSlots = (
    id: string,
    putApiDashboardsByIdSlotsBody?: PutApiDashboardsByIdSlotsBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PutApiDashboardsByIdSlots200>> => {
    return axiosInstance.put(
      `/api/dashboards/${id}/slots`,
      putApiDashboardsByIdSlotsBody,
      options,
    );
  };

  /**
   * List all data sources for the caller's project
   */
  const getApiDatasources = (
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<GetApiDatasources200Item[]>> => {
    return axiosInstance.get(`/api/datasources`, options);
  };

  /**
   * Create a new data source in the caller's project
   */
  const postApiDatasources = (
    postApiDatasourcesBody?: PostApiDatasourcesBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PostApiDatasources201>> => {
    return axiosInstance.post(
      `/api/datasources`,
      postApiDatasourcesBody,
      options,
    );
  };

  /**
   * Get a single data source by id
   */
  const getApiDatasourcesById = (
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<GetApiDatasourcesById200>> => {
    return axiosInstance.get(`/api/datasources/${id}`, options);
  };

  /**
   * Update a data source
   */
  const putApiDatasourcesById = (
    id: string,
    putApiDatasourcesByIdBody?: PutApiDatasourcesByIdBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PutApiDatasourcesById200>> => {
    return axiosInstance.put(
      `/api/datasources/${id}`,
      putApiDatasourcesByIdBody,
      options,
    );
  };

  /**
   * Delete a data source
   */
  const deleteApiDatasourcesById = (
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(`/api/datasources/${id}`, options);
  };

  /**
   * List all charts linked to a data source
   */
  const getApiDatasourcesByIdLinks = (
    id: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<GetApiDatasourcesByIdLinks200Item[]>> => {
    return axiosInstance.get(`/api/datasources/${id}/links`, options);
  };

  /**
   * Link a chart to a data source
   */
  const postApiDatasourcesByIdLinks = (
    id: string,
    postApiDatasourcesByIdLinksBody?: PostApiDatasourcesByIdLinksBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PostApiDatasourcesByIdLinks201>> => {
    return axiosInstance.post(
      `/api/datasources/${id}/links`,
      postApiDatasourcesByIdLinksBody,
      options,
    );
  };

  /**
   * Remove a chart-datasource link
   */
  const deleteApiDatasourcesByIdLinksByChartId = (
    id: string,
    chartId: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/datasources/${id}/links/${chartId}`,
      options,
    );
  };

  const postApiHints = (
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PostApiHints200Item[]>> => {
    return axiosInstance.post(`/api/hints`, undefined, options);
  };

  /**
   * List all orgs the current user belongs to
   */
  const getApiOrgs = (
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<GetApiOrgs200Item[]>> => {
    return axiosInstance.get(`/api/orgs`, options);
  };

  /**
   * Create a new org. The current user becomes its first ADMIN member.
   */
  const postApiOrgs = (
    postApiOrgsBody?: PostApiOrgsBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PostApiOrgs201>> => {
    return axiosInstance.post(`/api/orgs`, postApiOrgsBody, options);
  };

  /**
   * Get a single org with its members and associated projects
   */
  const getApiOrgsByOrgId = (
    orgId: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<GetApiOrgsByOrgId200>> => {
    return axiosInstance.get(`/api/orgs/${orgId}`, options);
  };

  /**
   * Rename an org (ADMIN only)
   */
  const putApiOrgsByOrgId = (
    orgId: string,
    putApiOrgsByOrgIdBody?: PutApiOrgsByOrgIdBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PutApiOrgsByOrgId200>> => {
    return axiosInstance.put(
      `/api/orgs/${orgId}`,
      putApiOrgsByOrgIdBody,
      options,
    );
  };

  /**
   * Delete an org (ADMIN only)
   */
  const deleteApiOrgsByOrgId = (
    orgId: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(`/api/orgs/${orgId}`, options);
  };

  /**
   * List members of an org (members only)
   */
  const getApiOrgsByOrgIdMembers = (
    orgId: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<GetApiOrgsByOrgIdMembers200Item[]>> => {
    return axiosInstance.get(`/api/orgs/${orgId}/members`, options);
  };

  /**
   * Add a user to an org (ADMIN only)
   */
  const postApiOrgsByOrgIdMembers = (
    orgId: string,
    postApiOrgsByOrgIdMembersBody?: PostApiOrgsByOrgIdMembersBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PostApiOrgsByOrgIdMembers201>> => {
    return axiosInstance.post(
      `/api/orgs/${orgId}/members`,
      postApiOrgsByOrgIdMembersBody,
      options,
    );
  };

  /**
   * List projects of an org (members only)
   */
  const getApiOrgsByOrgIdProjects = (
    orgId: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.get(`/api/orgs/${orgId}/projects`, options);
  };

  /**
   * Update a member's role in an org (ADMIN only)
   */
  const putApiOrgsByOrgIdMembersByUserId = (
    orgId: string,
    userId: string,
    putApiOrgsByOrgIdMembersByUserIdBody?: PutApiOrgsByOrgIdMembersByUserIdBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PutApiOrgsByOrgIdMembersByUserId200>> => {
    return axiosInstance.put(
      `/api/orgs/${orgId}/members/${userId}`,
      putApiOrgsByOrgIdMembersByUserIdBody,
      options,
    );
  };

  /**
   * Remove a member from an org (ADMIN only)
   */
  const deleteApiOrgsByOrgIdMembersByUserId = (
    orgId: string,
    userId: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/orgs/${orgId}/members/${userId}`,
      options,
    );
  };

  /**
   * List all projects the current user owns or is a member of.
   */
  const getApiProjects = (
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<GetApiProjects200Item[]>> => {
    return axiosInstance.get(`/api/projects`, options);
  };

  /**
   * Create a new project. The current user becomes owner and ADMIN member automatically.
   */
  const postApiProjects = (
    postApiProjectsBody?: PostApiProjectsBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PostApiProjects201>> => {
    return axiosInstance.post(`/api/projects`, postApiProjectsBody, options);
  };

  /**
   * List projects owned by the current user that are not associated with any org.
   */
  const getApiProjectsPersonal = (
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<GetApiProjectsPersonal200Item[]>> => {
    return axiosInstance.get(`/api/projects/personal`, options);
  };

  /**
   * Get a project by ID. Accessible to the owner and its members.
   */
  const getApiProjectsByProjectId = (
    projectId: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<GetApiProjectsByProjectId200>> => {
    return axiosInstance.get(`/api/projects/${projectId}`, options);
  };

  /**
   * Rename a project. Requires ADMIN or owner access.
   */
  const putApiProjectsByProjectId = (
    projectId: string,
    putApiProjectsByProjectIdBody?: PutApiProjectsByProjectIdBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PutApiProjectsByProjectId200>> => {
    return axiosInstance.put(
      `/api/projects/${projectId}`,
      putApiProjectsByProjectIdBody,
      options,
    );
  };

  /**
   * Delete a project. Owner only.
   */
  const deleteApiProjectsByProjectId = (
    projectId: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(`/api/projects/${projectId}`, options);
  };

  /**
   * List members of a project. Requires ADMIN or owner access.
   */
  const getApiProjectsByProjectIdMembers = (
    projectId: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<GetApiProjectsByProjectIdMembers200Item[]>> => {
    return axiosInstance.get(`/api/projects/${projectId}/members`, options);
  };

  /**
   * Add a user to a project. Requires ADMIN or owner access.
   */
  const postApiProjectsByProjectIdMembers = (
    projectId: string,
    postApiProjectsByProjectIdMembersBody?: PostApiProjectsByProjectIdMembersBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PostApiProjectsByProjectIdMembers201>> => {
    return axiosInstance.post(
      `/api/projects/${projectId}/members`,
      postApiProjectsByProjectIdMembersBody,
      options,
    );
  };

  /**
   * Change the role of a project member. Requires ADMIN or owner access.
   */
  const putApiProjectsByProjectIdMembersByUserId = (
    projectId: string,
    userId: string,
    putApiProjectsByProjectIdMembersByUserIdBody?: PutApiProjectsByProjectIdMembersByUserIdBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<PutApiProjectsByProjectIdMembersByUserId200>> => {
    return axiosInstance.put(
      `/api/projects/${projectId}/members/${userId}`,
      putApiProjectsByProjectIdMembersByUserIdBody,
      options,
    );
  };

  /**
   * Remove a member from a project. Requires ADMIN or owner access.
   */
  const deleteApiProjectsByProjectIdMembersByUserId = (
    projectId: string,
    userId: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/projects/${projectId}/members/${userId}`,
      options,
    );
  };

  /**
   * Associate an org with a project. Requires ADMIN or owner access.
   */
  const postApiProjectsByProjectIdOrgs = (
    projectId: string,
    postApiProjectsByProjectIdOrgsBody?: PostApiProjectsByProjectIdOrgsBody,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<unknown>> => {
    return axiosInstance.post(
      `/api/projects/${projectId}/orgs`,
      postApiProjectsByProjectIdOrgsBody,
      options,
    );
  };

  /**
   * Remove an org association from a project. Owner only.
   */
  const deleteApiProjectsByProjectIdOrgsByOrgId = (
    projectId: string,
    orgId: string,
    options?: AxiosRequestConfig,
  ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/projects/${projectId}/orgs/${orgId}`,
      options,
    );
  };

  return {
    getApiAdminUsers,
    deleteApiAdminUsersById,
    postApiAdminUsersByIdActivate,
    postApiAdminUsersByIdResendActivation,
    postApiAdminUsersByIdResetPassword,
    getApiAuthUser,
    postApiAuthRegister,
    postApiAuthLogin,
    postApiAuthRecover,
    postApiAuthResend,
    getApiAuthLogout,
    postApiAuthVerify,
    getApiAuthConfirmByUidByCode,
    postApiAuthResetPassword,
    putApiAuthPwd,
    getApiApikeys,
    postApiApikeys,
    deleteApiApikeysById,
    patchApiApikeysByIdRevoke,
    patchApiApikeysByIdReinstate,
    getApiApikeysByIdLogs,
    getApiCharts,
    postApiCharts,
    getApiChartsById,
    deleteApiChartsById,
    putApiChartsById,
    getApiChartsShowById,
    postApiChartsPublishById,
    postApiChartsKpiGroup,
    putApiChartsKpiGroupById,
    getApiChartsKpiGroupById,
    getApiDashboards,
    postApiDashboards,
    getApiDashboardsById,
    deleteApiDashboardsById,
    putApiDashboardsById,
    getApiDashboardsShowById,
    putApiDashboardsByIdSlots,
    getApiDatasources,
    postApiDatasources,
    getApiDatasourcesById,
    putApiDatasourcesById,
    deleteApiDatasourcesById,
    getApiDatasourcesByIdLinks,
    postApiDatasourcesByIdLinks,
    deleteApiDatasourcesByIdLinksByChartId,
    postApiHints,
    getApiOrgs,
    postApiOrgs,
    getApiOrgsByOrgId,
    putApiOrgsByOrgId,
    deleteApiOrgsByOrgId,
    getApiOrgsByOrgIdMembers,
    postApiOrgsByOrgIdMembers,
    getApiOrgsByOrgIdProjects,
    putApiOrgsByOrgIdMembersByUserId,
    deleteApiOrgsByOrgIdMembersByUserId,
    getApiProjects,
    postApiProjects,
    getApiProjectsPersonal,
    getApiProjectsByProjectId,
    putApiProjectsByProjectId,
    deleteApiProjectsByProjectId,
    getApiProjectsByProjectIdMembers,
    postApiProjectsByProjectIdMembers,
    putApiProjectsByProjectIdMembersByUserId,
    deleteApiProjectsByProjectIdMembersByUserId,
    postApiProjectsByProjectIdOrgs,
    deleteApiProjectsByProjectIdOrgsByOrgId,
  };
};
export type GetApiAdminUsersResult = AxiosResponse<void>;
export type DeleteApiAdminUsersByIdResult = AxiosResponse<void>;
export type PostApiAdminUsersByIdActivateResult = AxiosResponse<void>;
export type PostApiAdminUsersByIdResendActivationResult = AxiosResponse<void>;
export type PostApiAdminUsersByIdResetPasswordResult = AxiosResponse<void>;
export type GetApiAuthUserResult = AxiosResponse<GetApiAuthUser201>;
export type PostApiAuthRegisterResult = AxiosResponse<PostApiAuthRegister200>;
export type PostApiAuthLoginResult = AxiosResponse<PostApiAuthLogin200>;
export type PostApiAuthRecoverResult = AxiosResponse<boolean>;
export type PostApiAuthResendResult = AxiosResponse<boolean>;
export type GetApiAuthLogoutResult = AxiosResponse<boolean>;
export type PostApiAuthVerifyResult = AxiosResponse<PostApiAuthVerify200>;
export type GetApiAuthConfirmByUidByCodeResult = AxiosResponse<unknown>;
export type PostApiAuthResetPasswordResult =
  AxiosResponse<PostApiAuthResetPassword200>;
export type PutApiAuthPwdResult = AxiosResponse<void>;
export type GetApiApikeysResult = AxiosResponse<GetApiApikeys200Item[]>;
export type PostApiApikeysResult = AxiosResponse<PostApiApikeys201>;
export type DeleteApiApikeysByIdResult = AxiosResponse<void>;
export type PatchApiApikeysByIdRevokeResult =
  AxiosResponse<PatchApiApikeysByIdRevoke200>;
export type PatchApiApikeysByIdReinstateResult =
  AxiosResponse<PatchApiApikeysByIdReinstate200>;
export type GetApiApikeysByIdLogsResult = AxiosResponse<
  GetApiApikeysByIdLogs200Item[]
>;
export type GetApiChartsResult = AxiosResponse<GetApiCharts200Item[]>;
export type PostApiChartsResult = AxiosResponse<PostApiCharts201>;
export type GetApiChartsByIdResult = AxiosResponse<GetApiChartsById200>;
export type DeleteApiChartsByIdResult = AxiosResponse<DeleteApiChartsById200>;
export type PutApiChartsByIdResult = AxiosResponse<PutApiChartsById200>;
export type GetApiChartsShowByIdResult = AxiosResponse<GetApiChartsShowById200>;
export type PostApiChartsPublishByIdResult =
  AxiosResponse<PostApiChartsPublishById200>;
export type PostApiChartsKpiGroupResult =
  AxiosResponse<PostApiChartsKpiGroup201>;
export type PutApiChartsKpiGroupByIdResult =
  AxiosResponse<PutApiChartsKpiGroupById200>;
export type GetApiChartsKpiGroupByIdResult =
  AxiosResponse<GetApiChartsKpiGroupById200>;
export type GetApiDashboardsResult = AxiosResponse<GetApiDashboards200Item[]>;
export type PostApiDashboardsResult = AxiosResponse<PostApiDashboards201>;
export type GetApiDashboardsByIdResult = AxiosResponse<GetApiDashboardsById200>;
export type DeleteApiDashboardsByIdResult = AxiosResponse<void>;
export type PutApiDashboardsByIdResult = AxiosResponse<PutApiDashboardsById200>;
export type GetApiDashboardsShowByIdResult =
  AxiosResponse<GetApiDashboardsShowById200>;
export type PutApiDashboardsByIdSlotsResult =
  AxiosResponse<PutApiDashboardsByIdSlots200>;
export type GetApiDatasourcesResult = AxiosResponse<GetApiDatasources200Item[]>;
export type PostApiDatasourcesResult = AxiosResponse<PostApiDatasources201>;
export type GetApiDatasourcesByIdResult =
  AxiosResponse<GetApiDatasourcesById200>;
export type PutApiDatasourcesByIdResult =
  AxiosResponse<PutApiDatasourcesById200>;
export type DeleteApiDatasourcesByIdResult = AxiosResponse<void>;
export type GetApiDatasourcesByIdLinksResult = AxiosResponse<
  GetApiDatasourcesByIdLinks200Item[]
>;
export type PostApiDatasourcesByIdLinksResult =
  AxiosResponse<PostApiDatasourcesByIdLinks201>;
export type DeleteApiDatasourcesByIdLinksByChartIdResult = AxiosResponse<void>;
export type PostApiHintsResult = AxiosResponse<PostApiHints200Item[]>;
export type GetApiOrgsResult = AxiosResponse<GetApiOrgs200Item[]>;
export type PostApiOrgsResult = AxiosResponse<PostApiOrgs201>;
export type GetApiOrgsByOrgIdResult = AxiosResponse<GetApiOrgsByOrgId200>;
export type PutApiOrgsByOrgIdResult = AxiosResponse<PutApiOrgsByOrgId200>;
export type DeleteApiOrgsByOrgIdResult = AxiosResponse<void>;
export type GetApiOrgsByOrgIdMembersResult = AxiosResponse<
  GetApiOrgsByOrgIdMembers200Item[]
>;
export type PostApiOrgsByOrgIdMembersResult =
  AxiosResponse<PostApiOrgsByOrgIdMembers201>;
export type GetApiOrgsByOrgIdProjectsResult = AxiosResponse<unknown>;
export type PutApiOrgsByOrgIdMembersByUserIdResult =
  AxiosResponse<PutApiOrgsByOrgIdMembersByUserId200>;
export type DeleteApiOrgsByOrgIdMembersByUserIdResult = AxiosResponse<void>;
export type GetApiProjectsResult = AxiosResponse<GetApiProjects200Item[]>;
export type PostApiProjectsResult = AxiosResponse<PostApiProjects201>;
export type GetApiProjectsPersonalResult = AxiosResponse<
  GetApiProjectsPersonal200Item[]
>;
export type GetApiProjectsByProjectIdResult =
  AxiosResponse<GetApiProjectsByProjectId200>;
export type PutApiProjectsByProjectIdResult =
  AxiosResponse<PutApiProjectsByProjectId200>;
export type DeleteApiProjectsByProjectIdResult = AxiosResponse<void>;
export type GetApiProjectsByProjectIdMembersResult = AxiosResponse<
  GetApiProjectsByProjectIdMembers200Item[]
>;
export type PostApiProjectsByProjectIdMembersResult =
  AxiosResponse<PostApiProjectsByProjectIdMembers201>;
export type PutApiProjectsByProjectIdMembersByUserIdResult =
  AxiosResponse<PutApiProjectsByProjectIdMembersByUserId200>;
export type DeleteApiProjectsByProjectIdMembersByUserIdResult =
  AxiosResponse<void>;
export type PostApiProjectsByProjectIdOrgsResult = AxiosResponse<unknown>;
export type DeleteApiProjectsByProjectIdOrgsByOrgIdResult = AxiosResponse<void>;
