{{- if and .Values.imagePullSecret.enabled .Values.imagePullSecret.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dataviz.fullname" . }}-image-pull-secret
  labels:
    {{- include "dataviz.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}

