{{- if .Values.podDisruptionBudget.enabled }}
{{- if .Values.webapp.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "dataviz.fullname" . }}-webapp
  labels:
    {{- include "dataviz.labels" . | nindent 4 }}
    component: webapp
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dataviz.selectorLabels" . | nindent 6 }}
      component: webapp
{{- end }}
{{- if and .Values.webapp.enabled .Values.server.enabled }}
---
{{- end }}
{{- if .Values.server.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "dataviz.fullname" . }}-server
  labels:
    {{- include "dataviz.labels" . | nindent 4 }}
    component: server
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- else if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dataviz.selectorLabels" . | nindent 6 }}
      component: server
{{- end }}
{{- end }}

