{{- if .Values.webapp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dataviz.fullname" . }}-webapp
  labels:
    {{- include "dataviz.labels" . | nindent 4 }}
    component: webapp
spec:
  type: {{ .Values.webapp.service.type }}
  ports:
    - port: {{ .Values.webapp.service.port }}
      targetPort: {{ .Values.webapp.containerPort | default 80 }}
      protocol: TCP
      name: http
  selector:
    {{- include "dataviz.selectorLabels" . | nindent 4 }}
    component: webapp
{{- end }}

