/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */

export type GetApiApikeys200ItemRole =
  (typeof GetApiApikeys200ItemRole)[keyof typeof GetApiApikeys200ItemRole];

export const GetApiApikeys200ItemRole = {
  READONLY: "READONLY",
  READWRITE: "READWRITE",
} as const;
