/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */

export type GetApiApikeysByIdLogs200Item = {
  id: string;
  method: string;
  endpoint: string;
  status: number;
  responseTime: number;
  timestamp: string;
  apiKeyId: string | null;
  projectName: string | null;
};
