/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiApikeys200ItemRole } from "./getApiApikeys200ItemRole.js";

export type GetApiApikeys200Item = {
  id: string;
  prefix: string;
  role: GetApiApikeys200ItemRole;
  expire: number;
  revokedAt: string | null;
  projectId: string;
  createdAt: string;
  updatedAt: string;
};
