/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */

export type GetApiDatasources200Item = {
  id: string;
  projectId: string;
  name: string | null;
  description: string | null;
  data: unknown;
  rules: unknown | null;
  publish: boolean;
  isTrasposed: boolean;
  remoteUrl: string | null;
  isRemote: boolean;
  createdAt: string;
  updatedAt: string;
};
