/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiProjectsByProjectIdMembers200ItemRole } from "./getApiProjectsByProjectIdMembers200ItemRole.js";

export type GetApiProjectsByProjectIdMembers200Item = {
  userId: string;
  projectId: string;
  role: GetApiProjectsByProjectIdMembers200ItemRole;
  createdAt: string;
  updatedAt: string;
};
