/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */

export type GetApiOrgsByOrgIdMembers200ItemRole =
  (typeof GetApiOrgsByOrgIdMembers200ItemRole)[keyof typeof GetApiOrgsByOrgIdMembers200ItemRole];

export const GetApiOrgsByOrgIdMembers200ItemRole = {
  USER: "USER",
  ADMIN: "ADMIN",
} as const;
