/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */

export type GetApiChartsKpiGroupById200DataDataSourceItemFlowDirection =
  (typeof GetApiChartsKpiGroupById200DataDataSourceItemFlowDirection)[keyof typeof GetApiChartsKpiGroupById200DataDataSourceItemFlowDirection];

export const GetApiChartsKpiGroupById200DataDataSourceItemFlowDirection = {
  "+": "+",
  "-": "-",
} as const;
