/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */

export type GetApiProjectsByProjectIdMembers200ItemRole =
  (typeof GetApiProjectsByProjectIdMembers200ItemRole)[keyof typeof GetApiProjectsByProjectIdMembers200ItemRole];

export const GetApiProjectsByProjectIdMembers200ItemRole = {
  USER: "USER",
  ADMIN: "ADMIN",
} as const;
