/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiChartsKpiGroupById200DataDataSourceItem } from "./getApiChartsKpiGroupById200DataDataSourceItem.js";

export type GetApiChartsKpiGroupById200Data = {
  id: string;
  name: string | null;
  description: string | null;
  config: unknown;
  dataSource: GetApiChartsKpiGroupById200DataDataSourceItem[];
};
