/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiOrgsByOrgIdMembers200ItemRole } from "./getApiOrgsByOrgIdMembers200ItemRole.js";

export type GetApiOrgsByOrgIdMembers200Item = {
  userId: string;
  orgId: string;
  role: GetApiOrgsByOrgIdMembers200ItemRole;
  createdAt: string;
  updatedAt: string;
};
