/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiApikeysByIdRevoke200Role =
  (typeof PatchApiApikeysByIdRevoke200Role)[keyof typeof PatchApiApikeysByIdRevoke200Role];

export const PatchApiApikeysByIdRevoke200Role = {
  READONLY: "READONLY",
  READWRITE: "READWRITE",
} as const;
