/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */
import type { PatchApiApikeysByIdRevoke200Role } from "./patchApiApikeysByIdRevoke200Role.js";

export type PatchApiApikeysByIdRevoke200 = {
  id: string;
  prefix: string;
  role: PatchApiApikeysByIdRevoke200Role;
  expire: number;
  revokedAt: string | null;
  projectId: string;
  createdAt: string;
  updatedAt: string;
};
