/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */

export type PatchApiApikeysByIdReinstate200Role =
  (typeof PatchApiApikeysByIdReinstate200Role)[keyof typeof PatchApiApikeysByIdReinstate200Role];

export const PatchApiApikeysByIdReinstate200Role = {
  READONLY: "READONLY",
  READWRITE: "READWRITE",
} as const;
