/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiProjectsByProjectIdMembers201Role } from "./postApiProjectsByProjectIdMembers201Role.js";

export type PostApiProjectsByProjectIdMembers201 = {
  userId: string;
  projectId: string;
  role: PostApiProjectsByProjectIdMembers201Role;
  createdAt: string;
  updatedAt: string;
};
