/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */

export type PostApiProjects201 = {
  id: string;
  name: string;
  ownerId: string;
  createdAt: string;
  updatedAt: string;
};
