/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */

export type PostApiHints200Item = {
  hint: string;
  /**
   * @minimum 0
   * @maximum 1
   */
  confidence: number;
};
