/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */

export type PostApiOrgsByOrgIdMembers201Role =
  (typeof PostApiOrgsByOrgIdMembers201Role)[keyof typeof PostApiOrgsByOrgIdMembers201Role];

export const PostApiOrgsByOrgIdMembers201Role = {
  USER: "USER",
  ADMIN: "ADMIN",
} as const;
