/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiApikeys201Role } from "./postApiApikeys201Role.js";

export type PostApiApikeys201 = {
  id: string;
  prefix: string;
  role: PostApiApikeys201Role;
  expire: number;
  revokedAt: string | null;
  projectId: string;
  createdAt: string;
  updatedAt: string;
};
