/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */

export type PostApiDashboardsBody = {
  name?: string;
  description?: string;
  config?: unknown;
  data?: unknown;
  remoteUrl?: string | null;
  isRemote?: boolean;
  publish?: boolean;
  preview?: string | null;
  projectId?: string;
};
