/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */

export type PostApiApikeys201Role =
  (typeof PostApiApikeys201Role)[keyof typeof PostApiApikeys201Role];

export const PostApiApikeys201Role = {
  READONLY: "READONLY",
  READWRITE: "READWRITE",
} as const;
