/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */

export type PostApiProjectsByProjectIdMembers201Role =
  (typeof PostApiProjectsByProjectIdMembers201Role)[keyof typeof PostApiProjectsByProjectIdMembers201Role];

export const PostApiProjectsByProjectIdMembers201Role = {
  USER: "USER",
  ADMIN: "ADMIN",
} as const;
