/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiOrgsByOrgIdMembers201Role } from "./postApiOrgsByOrgIdMembers201Role.js";

export type PostApiOrgsByOrgIdMembers201 = {
  userId: string;
  orgId: string;
  role: PostApiOrgsByOrgIdMembers201Role;
  createdAt: string;
  updatedAt: string;
};
