/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */

export type PostApiProjectsByProjectIdMembersBodyRole =
  (typeof PostApiProjectsByProjectIdMembersBodyRole)[keyof typeof PostApiProjectsByProjectIdMembersBodyRole];

export const PostApiProjectsByProjectIdMembersBodyRole = {
  USER: "USER",
  ADMIN: "ADMIN",
} as const;
