/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiApikeysBodyRole } from "./postApiApikeysBodyRole.js";

export type PostApiApikeysBody = {
  role?: PostApiApikeysBodyRole;
  /**
   * @maximum 9007199254740991
   * @exclusiveMinimum 0
   */
  expire?: number;
  projectId?: string;
};
