/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */

export type PutApiProjectsByProjectIdMembersByUserId200Role =
  (typeof PutApiProjectsByProjectIdMembersByUserId200Role)[keyof typeof PutApiProjectsByProjectIdMembersByUserId200Role];

export const PutApiProjectsByProjectIdMembersByUserId200Role = {
  USER: "USER",
  ADMIN: "ADMIN",
} as const;
