/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiDashboardsByIdSlotsBodySlotsItemSettings } from "./putApiDashboardsByIdSlotsBodySlotsItemSettings.js";

export type PutApiDashboardsByIdSlotsBodySlotsItem = {
  chartId: string;
  settings?: PutApiDashboardsByIdSlotsBodySlotsItemSettings;
  createdAt?: string;
  updatedAt?: string;
};
