/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */

export type PutApiChartsKpiGroupByIdBodyConfigDirection =
  (typeof PutApiChartsKpiGroupByIdBodyConfigDirection)[keyof typeof PutApiChartsKpiGroupByIdBodyConfigDirection];

export const PutApiChartsKpiGroupByIdBodyConfigDirection = {
  vertical: "vertical",
  horizontal: "horizontal",
} as const;
