/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiProjectsByProjectIdMembersByUserId200Role } from "./putApiProjectsByProjectIdMembersByUserId200Role.js";

export type PutApiProjectsByProjectIdMembersByUserId200 = {
  userId: string;
  projectId: string;
  role: PutApiProjectsByProjectIdMembersByUserId200Role;
  createdAt: string;
  updatedAt: string;
};
