/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiOrgsByOrgIdMembersByUserId200Role } from "./putApiOrgsByOrgIdMembersByUserId200Role.js";

export type PutApiOrgsByOrgIdMembersByUserId200 = {
  userId: string;
  orgId: string;
  role: PutApiOrgsByOrgIdMembersByUserId200Role;
  createdAt: string;
  updatedAt: string;
};
