/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiChartsKpiGroupByIdBodyDataSourceItemFlowDirection } from "./putApiChartsKpiGroupByIdBodyDataSourceItemFlowDirection.js";

export type PutApiChartsKpiGroupByIdBodyDataSourceItem = {
  title: string;
  value: string;
  percentage?: string;
  background_color?: string;
  value_prefix?: string;
  value_suffix?: string;
  show_flow: boolean;
  flow_value: string;
  flow_direction: PutApiChartsKpiGroupByIdBodyDataSourceItemFlowDirection;
  flow_detail?: string;
  footer_text?: string;
};
