/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */

export type PutApiChartsByIdBody = {
  name?: string;
  description?: string;
  chart?: string;
  config?: unknown;
  data?: unknown;
  dataSource?: unknown;
  publish?: boolean;
  remoteUrl?: string | null;
  isRemote?: boolean;
  id?: string;
  preview?: string | null;
  slots?: string[] | null;
};
