/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiChartsKpiGroupByIdBodyConfigDirection } from "./putApiChartsKpiGroupByIdBodyConfigDirection.js";

export type PutApiChartsKpiGroupByIdBodyConfig = {
  direction: PutApiChartsKpiGroupByIdBodyConfigDirection;
  h: number;
  labeLine: boolean;
  legend: boolean;
  legendPosition: string;
  palette: string[];
  tooltip: boolean;
  tooltipFormatter: string;
  valueFormatter: string;
  totalLabel: string;
  tooltipTrigger: string;
  colors: string[];
  background: string;
};
