/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiDashboardsByIdBodySlotsItemSettings } from "./putApiDashboardsByIdBodySlotsItemSettings.js";

export type PutApiDashboardsByIdBodySlotsItem = {
  chartId: string;
  settings?: PutApiDashboardsByIdBodySlotsItemSettings;
  createdAt?: string;
  updatedAt?: string;
};
