/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */

export type PutApiChartsKpiGroupByIdBodyDataSourceItemFlowDirection =
  (typeof PutApiChartsKpiGroupByIdBodyDataSourceItemFlowDirection)[keyof typeof PutApiChartsKpiGroupByIdBodyDataSourceItemFlowDirection];

export const PutApiChartsKpiGroupByIdBodyDataSourceItemFlowDirection = {
  "+": "+",
  "-": "-",
} as const;
