/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */

export type PutApiChartsById200 = {
  id: string;
  projectId: string;
  name: string | null;
  description: string | null;
  chart: string;
  dataSource?: unknown;
  config: unknown | null;
  data: unknown | null;
  isRemote: boolean | null;
  remoteUrl: string | null;
  publish: boolean;
  createdAt: string;
  updatedAt: string;
};
