/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */

export type PutApiOrgsByOrgIdMembersByUserId200Role =
  (typeof PutApiOrgsByOrgIdMembersByUserId200Role)[keyof typeof PutApiOrgsByOrgIdMembersByUserId200Role];

export const PutApiOrgsByOrgIdMembersByUserId200Role = {
  USER: "USER",
  ADMIN: "ADMIN",
} as const;
