/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Graph Italia API
 * API documentation for the Graph Italia application
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiChartsKpiGroupByIdBodyConfig } from "./putApiChartsKpiGroupByIdBodyConfig.js";
import type { PutApiChartsKpiGroupByIdBodyDataSourceItem } from "./putApiChartsKpiGroupByIdBodyDataSourceItem.js";

export type PutApiChartsKpiGroupByIdBody = {
  name: string;
  description?: string;
  publish?: boolean;
  config: PutApiChartsKpiGroupByIdBodyConfig;
  dataSource: PutApiChartsKpiGroupByIdBodyDataSourceItem[];
};
