{{- if .Values.webapp.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graph-italia.fullname" . }}-webapp-config
  labels:
    {{- include "graph-italia.labels" . | nindent 4 }}
    component: webapp
data:
  config.json: |
    {
      "VITE_SERVER_URL": {{ if .Values.webapp.config.serverUrl }}{{ .Values.webapp.config.serverUrl | quote }}{{ else }}"http://localhost:3003"{{ end }}
    }
{{- end }}


